CREATE TABLE IF NOT EXISTS items (
  id      INTEGER PRIMARY KEY,
  status  INTEGER NOT NULL DEFAULT 0,
  link    TEXT    NOT NULL DEFAULT '',
  caption TEXT    NOT NULL DEFAULT '',
  notes   TEXT    NOT NULL DEFAULT '',
  updated TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS app_data (
  key     TEXT PRIMARY KEY,
  value   TEXT NOT NULL DEFAULT '{}',
  updated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS role_passwords (
  role       TEXT    PRIMARY KEY,
  hash       TEXT    NOT NULL,
  updated_at INTEGER NOT NULL DEFAULT 0
);
