CREATE TABLE IF NOT EXISTS items (
  id      INTEGER PRIMARY KEY,
  status  INTEGER NOT NULL DEFAULT 0,
  link    TEXT    NOT NULL DEFAULT '',
  caption TEXT    NOT NULL DEFAULT '',
  notes   TEXT    NOT NULL DEFAULT '',
  updated TEXT    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
