import type { Client, ContentItem } from './types'

export const CLIENTS: Client[] = [
  { name: 'Casa de Ração 2 Irmãos',  postsPerMonth: 4,  reelsPerMonth: 4  },
  { name: 'Chalés Alto da Represa',  postsPerMonth: 4,  reelsPerMonth: 4  },
  { name: "Frango d'Água",           postsPerMonth: 8,  reelsPerMonth: 4  },
  { name: 'Hidro Elétrica Andrade',  postsPerMonth: 4,  reelsPerMonth: 4  },
  { name: 'Home Elevadores',         postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'Kátia Bigatello',         postsPerMonth: 12, reelsPerMonth: 12 },
  { name: 'Lareiras Grill',          postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'Luthita',                 postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'LuzioPan',                postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'Magia dos Temáticos',     postsPerMonth: 6,  reelsPerMonth: 6  },
  { name: 'Padaria R.A',             postsPerMonth: 4,  reelsPerMonth: 4  },
  { name: 'Pousada Dukuka',          postsPerMonth: 6,  reelsPerMonth: 12 },
  { name: 'Quero Bolo',              postsPerMonth: 4,  reelsPerMonth: 4  },
  { name: 'ViniPlas',                postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'Rosângela Varas',         postsPerMonth: 6,  reelsPerMonth: 6  },
  { name: 'Compostela',              postsPerMonth: 8,  reelsPerMonth: 8  },
  { name: 'Suh Maya',                postsPerMonth: 4,  reelsPerMonth: 8  },
]

// Maio 2026 — alterar BASE_DATE e DATA para cada novo mês
export const BASE_DATE = new Date(2026, 4, 1)

const d = (day: number) => new Date(2026, 4, day)

// status: 3=publicado (dias passados), 1=em edição (hoje), 0=pendente (futuros)
const s = (day: number): 0 | 1 | 2 | 3 => day < 16 ? 3 : day === 16 ? 1 : 0

export const DATA: ContentItem[] = [

  // ── Casa de Ração 2 Irmãos ── 4 Posts · 4 Reels ─────
  { i:   1, c: 'Casa de Ração 2 Irmãos', dt: d( 3), tp: 'Post', n: 'Dicas de nutrição para seu pet',   s: s( 3) },
  { i:   2, c: 'Casa de Ração 2 Irmãos', dt: d(10), tp: 'Post', n: 'Produtos em promoção',             s: s(10) },
  { i:   3, c: 'Casa de Ração 2 Irmãos', dt: d(17), tp: 'Post', n: 'Cuidados com seu animal',          s: s(17) },
  { i:   4, c: 'Casa de Ração 2 Irmãos', dt: d(24), tp: 'Post', n: 'Novidades na loja',                s: s(24) },
  { i:   5, c: 'Casa de Ração 2 Irmãos', dt: d( 6), tp: 'Reel', n: 'Chegaram novidades!',             s: s( 6) },
  { i:   6, c: 'Casa de Ração 2 Irmãos', dt: d(13), tp: 'Reel', n: 'Tutorial: alimentação saudável',  s: s(13) },
  { i:   7, c: 'Casa de Ração 2 Irmãos', dt: d(20), tp: 'Reel', n: 'Pets da semana na loja',          s: s(20) },
  { i:   8, c: 'Casa de Ração 2 Irmãos', dt: d(27), tp: 'Reel', n: 'Promoção especial de maio',       s: s(27) },

  // ── Chalés Alto da Represa ── 4 Posts · 4 Reels ─────
  { i:   9, c: 'Chalés Alto da Represa', dt: d( 2), tp: 'Post', n: 'Vista da represa ao amanhecer',   s: s( 2) },
  { i:  10, c: 'Chalés Alto da Represa', dt: d( 9), tp: 'Post', n: 'Pacote fim de semana especial',   s: s( 9) },
  { i:  11, c: 'Chalés Alto da Represa', dt: d(16), tp: 'Post', n: 'Chalé para famílias',             s: s(16) },
  { i:  12, c: 'Chalés Alto da Represa', dt: d(23), tp: 'Post', n: 'Reserve para junho!',             s: s(23) },
  { i:  13, c: 'Chalés Alto da Represa', dt: d( 5), tp: 'Reel', n: 'Tour pelos nossos chalés',        s: s( 5) },
  { i:  14, c: 'Chalés Alto da Represa', dt: d(12), tp: 'Reel', n: 'Experiência dos hóspedes',        s: s(12) },
  { i:  15, c: 'Chalés Alto da Represa', dt: d(19), tp: 'Reel', n: 'Pôr do sol na represa',           s: s(19) },
  { i:  16, c: 'Chalés Alto da Represa', dt: d(26), tp: 'Reel', n: 'Atividades disponíveis',          s: s(26) },

  // ── Frango d'Água ── 8 Posts · 4 Reels ──────────────
  { i:  17, c: "Frango d'Água", dt: d( 2), tp: 'Post', n: 'Prato do dia: frango na brasa',           s: s( 2) },
  { i:  18, c: "Frango d'Água", dt: d( 5), tp: 'Post', n: 'Cardápio especial do mês',                s: s( 5) },
  { i:  19, c: "Frango d'Água", dt: d( 9), tp: 'Post', n: 'Promoção almoço executivo',               s: s( 9) },
  { i:  20, c: "Frango d'Água", dt: d(12), tp: 'Post', n: 'Novo item no cardápio',                   s: s(12) },
  { i:  21, c: "Frango d'Água", dt: d(16), tp: 'Post', n: 'Combo especial família',                  s: s(16) },
  { i:  22, c: "Frango d'Água", dt: d(20), tp: 'Post', n: 'Dica do chef',                            s: s(20) },
  { i:  23, c: "Frango d'Água", dt: d(24), tp: 'Post', n: 'Reserve sua mesa — junho',                s: s(24) },
  { i:  24, c: "Frango d'Água", dt: d(28), tp: 'Post', n: 'Encerre o mês com sabor',                 s: s(28) },
  { i:  25, c: "Frango d'Água", dt: d( 7), tp: 'Reel', n: 'Preparo do frango na brasa',              s: s( 7) },
  { i:  26, c: "Frango d'Água", dt: d(14), tp: 'Reel', n: 'Novidade no cardápio',                    s: s(14) },
  { i:  27, c: "Frango d'Água", dt: d(21), tp: 'Reel', n: 'Especial: frango caipira',                s: s(21) },
  { i:  28, c: "Frango d'Água", dt: d(29), tp: 'Reel', n: 'Tour pela nossa cozinha',                 s: s(29) },

  // ── Hidro Elétrica Andrade ── 4 Posts · 4 Reels ─────
  { i:  29, c: 'Hidro Elétrica Andrade', dt: d( 3), tp: 'Post', n: 'Instalação elétrica residencial', s: s( 3) },
  { i:  30, c: 'Hidro Elétrica Andrade', dt: d(10), tp: 'Post', n: 'Dica de segurança elétrica',      s: s(10) },
  { i:  31, c: 'Hidro Elétrica Andrade', dt: d(17), tp: 'Post', n: 'Projeto de painel solar',         s: s(17) },
  { i:  32, c: 'Hidro Elétrica Andrade', dt: d(24), tp: 'Post', n: 'Orçamento gratuito',              s: s(24) },
  { i:  33, c: 'Hidro Elétrica Andrade', dt: d( 7), tp: 'Reel', n: 'Nossa equipe em ação',            s: s( 7) },
  { i:  34, c: 'Hidro Elétrica Andrade', dt: d(14), tp: 'Reel', n: 'Antes e depois: projeto elétrico',s: s(14) },
  { i:  35, c: 'Hidro Elétrica Andrade', dt: d(21), tp: 'Reel', n: 'Dicas de economia de energia',   s: s(21) },
  { i:  36, c: 'Hidro Elétrica Andrade', dt: d(28), tp: 'Reel', n: 'Instalação completa',            s: s(28) },

  // ── Home Elevadores ── 8 Posts · 8 Reels ────────────
  { i:  37, c: 'Home Elevadores', dt: d( 2), tp: 'Post', n: 'Elevador residencial compacto',          s: s( 2) },
  { i:  38, c: 'Home Elevadores', dt: d( 5), tp: 'Post', n: 'Conforto e segurança em casa',           s: s( 5) },
  { i:  39, c: 'Home Elevadores', dt: d( 9), tp: 'Post', n: 'Conheça nossos modelos',                 s: s( 9) },
  { i:  40, c: 'Home Elevadores', dt: d(13), tp: 'Post', n: 'Instalação personalizada',               s: s(13) },
  { i:  41, c: 'Home Elevadores', dt: d(17), tp: 'Post', n: 'Elevador para seu projeto',              s: s(17) },
  { i:  42, c: 'Home Elevadores', dt: d(21), tp: 'Post', n: 'Manutenção preventiva',                  s: s(21) },
  { i:  43, c: 'Home Elevadores', dt: d(25), tp: 'Post', n: 'Consultoria gratuita',                   s: s(25) },
  { i:  44, c: 'Home Elevadores', dt: d(29), tp: 'Post', n: 'Tecnologia de ponta',                    s: s(29) },
  { i:  45, c: 'Home Elevadores', dt: d( 3), tp: 'Reel', n: 'Como funciona nosso elevador',           s: s( 3) },
  { i:  46, c: 'Home Elevadores', dt: d( 7), tp: 'Reel', n: 'Instalação residencial passo a passo',  s: s( 7) },
  { i:  47, c: 'Home Elevadores', dt: d(11), tp: 'Reel', n: 'Modelos disponíveis 2026',               s: s(11) },
  { i:  48, c: 'Home Elevadores', dt: d(15), tp: 'Reel', n: 'Depoimento de cliente',                  s: s(15) },
  { i:  49, c: 'Home Elevadores', dt: d(19), tp: 'Reel', n: 'Antes e depois da instalação',           s: s(19) },
  { i:  50, c: 'Home Elevadores', dt: d(23), tp: 'Reel', n: 'Tour: elevador panorâmico',              s: s(23) },
  { i:  51, c: 'Home Elevadores', dt: d(27), tp: 'Reel', n: 'Processo de instalação',                 s: s(27) },
  { i:  52, c: 'Home Elevadores', dt: d(31), tp: 'Reel', n: 'Benefícios do elevador residencial',     s: s(31) },

  // ── Kátia Bigatello ── 12 Posts · 12 Reels ──────────
  { i:  53, c: 'Kátia Bigatello', dt: d( 1), tp: 'Post', n: 'Maquiagem do dia',                      s: s( 1) },
  { i:  54, c: 'Kátia Bigatello', dt: d( 3), tp: 'Post', n: 'Tutorial lábios perfeitos',              s: s( 3) },
  { i:  55, c: 'Kátia Bigatello', dt: d( 6), tp: 'Post', n: 'Make para o trabalho',                   s: s( 6) },
  { i:  56, c: 'Kátia Bigatello', dt: d( 9), tp: 'Post', n: 'Look noite especial',                    s: s( 9) },
  { i:  57, c: 'Kátia Bigatello', dt: d(12), tp: 'Post', n: 'Tendências de maio',                     s: s(12) },
  { i:  58, c: 'Kátia Bigatello', dt: d(15), tp: 'Post', n: 'Cuidados com a pele',                    s: s(15) },
  { i:  59, c: 'Kátia Bigatello', dt: d(17), tp: 'Post', n: 'Dica de hidratação',                     s: s(17) },
  { i:  60, c: 'Kátia Bigatello', dt: d(20), tp: 'Post', n: 'Make simples e rápida',                  s: s(20) },
  { i:  61, c: 'Kátia Bigatello', dt: d(22), tp: 'Post', n: 'Transformação da semana',                s: s(22) },
  { i:  62, c: 'Kátia Bigatello', dt: d(25), tp: 'Post', n: 'Produto favorito',                       s: s(25) },
  { i:  63, c: 'Kátia Bigatello', dt: d(27), tp: 'Post', n: 'Make para formatura',                    s: s(27) },
  { i:  64, c: 'Kátia Bigatello', dt: d(30), tp: 'Post', n: 'Cores da temporada',                     s: s(30) },
  { i:  65, c: 'Kátia Bigatello', dt: d( 2), tp: 'Reel', n: 'Tutorial: make dia a dia',               s: s( 2) },
  { i:  66, c: 'Kátia Bigatello', dt: d( 4), tp: 'Reel', n: 'Transformação completa',                 s: s( 4) },
  { i:  67, c: 'Kátia Bigatello', dt: d( 7), tp: 'Reel', n: 'Preparação da pele',                     s: s( 7) },
  { i:  68, c: 'Kátia Bigatello', dt: d(10), tp: 'Reel', n: 'Make para noiva',                        s: s(10) },
  { i:  69, c: 'Kátia Bigatello', dt: d(13), tp: 'Reel', n: 'Produtos que uso todo dia',              s: s(13) },
  { i:  70, c: 'Kátia Bigatello', dt: d(16), tp: 'Reel', n: 'Tutorial lábios nude',                   s: s(16) },
  { i:  71, c: 'Kátia Bigatello', dt: d(19), tp: 'Reel', n: 'Make estilo anos 60',                    s: s(19) },
  { i:  72, c: 'Kátia Bigatello', dt: d(21), tp: 'Reel', n: 'Correção de imperfeições',               s: s(21) },
  { i:  73, c: 'Kátia Bigatello', dt: d(24), tp: 'Reel', n: '5 dicas de make',                        s: s(24) },
  { i:  74, c: 'Kátia Bigatello', dt: d(26), tp: 'Reel', n: 'Blush placement 2026',                   s: s(26) },
  { i:  75, c: 'Kátia Bigatello', dt: d(28), tp: 'Reel', n: 'Make para casamento',                    s: s(28) },
  { i:  76, c: 'Kátia Bigatello', dt: d(31), tp: 'Reel', n: 'Rotina de cuidados',                     s: s(31) },

  // ── Lareiras Grill ── 8 Posts · 8 Reels ─────────────
  { i:  77, c: 'Lareiras Grill', dt: d( 3), tp: 'Post', n: 'Corte nobre da semana',                   s: s( 3) },
  { i:  78, c: 'Lareiras Grill', dt: d( 7), tp: 'Post', n: 'Cardápio especial fim de semana',         s: s( 7) },
  { i:  79, c: 'Lareiras Grill', dt: d(11), tp: 'Post', n: 'Reserve sua mesa',                        s: s(11) },
  { i:  80, c: 'Lareiras Grill', dt: d(15), tp: 'Post', n: 'Experiência única na Lareiras',           s: s(15) },
  { i:  81, c: 'Lareiras Grill', dt: d(19), tp: 'Post', n: 'Novo corte disponível',                   s: s(19) },
  { i:  82, c: 'Lareiras Grill', dt: d(22), tp: 'Post', n: 'Noite especial na Lareiras',              s: s(22) },
  { i:  83, c: 'Lareiras Grill', dt: d(26), tp: 'Post', n: 'Pacote para grupos',                      s: s(26) },
  { i:  84, c: 'Lareiras Grill', dt: d(30), tp: 'Post', n: 'Destaque do mês',                         s: s(30) },
  { i:  85, c: 'Lareiras Grill', dt: d( 5), tp: 'Reel', n: 'Preparo do churrasco perfeito',           s: s( 5) },
  { i:  86, c: 'Lareiras Grill', dt: d( 9), tp: 'Reel', n: 'Tour pelo restaurante',                   s: s( 9) },
  { i:  87, c: 'Lareiras Grill', dt: d(13), tp: 'Reel', n: 'Nossos cortes nobres',                    s: s(13) },
  { i:  88, c: 'Lareiras Grill', dt: d(17), tp: 'Reel', n: 'Noite à luz das lareiras',                s: s(17) },
  { i:  89, c: 'Lareiras Grill', dt: d(21), tp: 'Reel', n: 'Receita exclusiva do chef',               s: s(21) },
  { i:  90, c: 'Lareiras Grill', dt: d(24), tp: 'Reel', n: 'Experiência dos clientes',                s: s(24) },
  { i:  91, c: 'Lareiras Grill', dt: d(28), tp: 'Reel', n: 'Como é jantar na Lareiras',               s: s(28) },
  { i:  92, c: 'Lareiras Grill', dt: d(31), tp: 'Reel', n: 'Especial Dia dos Namorados',              s: s(31) },

  // ── Luthita ── 8 Posts · 8 Reels ────────────────────
  { i:  93, c: 'Luthita', dt: d( 1), tp: 'Post', n: 'Lookbook da semana',                             s: s( 1) },
  { i:  94, c: 'Luthita', dt: d( 5), tp: 'Post', n: 'Novidade na coleção',                            s: s( 5) },
  { i:  95, c: 'Luthita', dt: d( 8), tp: 'Post', n: 'Estilo do mês',                                  s: s( 8) },
  { i:  96, c: 'Luthita', dt: d(12), tp: 'Post', n: 'Peça destaque',                                  s: s(12) },
  { i:  97, c: 'Luthita', dt: d(16), tp: 'Post', n: 'Como usar esta semana',                          s: s(16) },
  { i:  98, c: 'Luthita', dt: d(20), tp: 'Post', n: 'Look casual chic',                               s: s(20) },
  { i:  99, c: 'Luthita', dt: d(24), tp: 'Post', n: 'Novos tons',                                     s: s(24) },
  { i: 100, c: 'Luthita', dt: d(28), tp: 'Post', n: 'Peça versátil',                                  s: s(28) },
  { i: 101, c: 'Luthita', dt: d( 3), tp: 'Reel', n: 'Unboxing coleção',                               s: s( 3) },
  { i: 102, c: 'Luthita', dt: d( 6), tp: 'Reel', n: 'Como combinar peças',                            s: s( 6) },
  { i: 103, c: 'Luthita', dt: d(10), tp: 'Reel', n: 'Look do dia',                                    s: s(10) },
  { i: 104, c: 'Luthita', dt: d(14), tp: 'Reel', n: 'Styling tips',                                   s: s(14) },
  { i: 105, c: 'Luthita', dt: d(18), tp: 'Reel', n: 'Novidades chegando',                             s: s(18) },
  { i: 106, c: 'Luthita', dt: d(22), tp: 'Reel', n: 'Haul de roupas',                                 s: s(22) },
  { i: 107, c: 'Luthita', dt: d(26), tp: 'Reel', n: '5 looks com uma peça',                           s: s(26) },
  { i: 108, c: 'Luthita', dt: d(30), tp: 'Reel', n: 'Looks para o trabalho',                          s: s(30) },

  // ── LuzioPan ── 8 Posts · 8 Reels ───────────────────
  { i: 109, c: 'LuzioPan', dt: d( 2), tp: 'Post', n: 'Pão fresquinho do dia',                        s: s( 2) },
  { i: 110, c: 'LuzioPan', dt: d( 6), tp: 'Post', n: 'Novidade no cardápio',                         s: s( 6) },
  { i: 111, c: 'LuzioPan', dt: d(10), tp: 'Post', n: 'Café da manhã especial',                       s: s(10) },
  { i: 112, c: 'LuzioPan', dt: d(14), tp: 'Post', n: 'Encomendas para eventos',                      s: s(14) },
  { i: 113, c: 'LuzioPan', dt: d(18), tp: 'Post', n: 'Doces artesanais',                             s: s(18) },
  { i: 114, c: 'LuzioPan', dt: d(22), tp: 'Post', n: 'Promoção da semana',                           s: s(22) },
  { i: 115, c: 'LuzioPan', dt: d(26), tp: 'Post', n: 'Produtos naturais',                            s: s(26) },
  { i: 116, c: 'LuzioPan', dt: d(30), tp: 'Post', n: 'Bolo do dia',                                  s: s(30) },
  { i: 117, c: 'LuzioPan', dt: d( 4), tp: 'Reel', n: 'Como fazemos nosso pão',                       s: s( 4) },
  { i: 118, c: 'LuzioPan', dt: d( 8), tp: 'Reel', n: 'Produção artesanal',                           s: s( 8) },
  { i: 119, c: 'LuzioPan', dt: d(12), tp: 'Reel', n: 'Novidade: novo sabor',                         s: s(12) },
  { i: 120, c: 'LuzioPan', dt: d(16), tp: 'Reel', n: 'Tour pela padaria',                            s: s(16) },
  { i: 121, c: 'LuzioPan', dt: d(20), tp: 'Reel', n: 'Processo de fermentação natural',              s: s(20) },
  { i: 122, c: 'LuzioPan', dt: d(24), tp: 'Reel', n: 'Receita exclusiva',                            s: s(24) },
  { i: 123, c: 'LuzioPan', dt: d(28), tp: 'Reel', n: 'Bolos personalizados',                         s: s(28) },
  { i: 124, c: 'LuzioPan', dt: d(31), tp: 'Reel', n: 'Café da manhã completo',                       s: s(31) },

  // ── Magia dos Temáticos ── 6 Posts · 6 Reels ────────
  { i: 125, c: 'Magia dos Temáticos', dt: d( 5), tp: 'Post', n: 'Festa temática dos sonhos',          s: s( 5) },
  { i: 126, c: 'Magia dos Temáticos', dt: d(10), tp: 'Post', n: 'Decoração incrível',                 s: s(10) },
  { i: 127, c: 'Magia dos Temáticos', dt: d(15), tp: 'Post', n: 'Reserve sua data',                   s: s(15) },
  { i: 128, c: 'Magia dos Temáticos', dt: d(20), tp: 'Post', n: 'Portfolio de festas',                s: s(20) },
  { i: 129, c: 'Magia dos Temáticos', dt: d(25), tp: 'Post', n: 'Tema exclusivo',                     s: s(25) },
  { i: 130, c: 'Magia dos Temáticos', dt: d(30), tp: 'Post', n: 'Festa adulto temática',              s: s(30) },
  { i: 131, c: 'Magia dos Temáticos', dt: d( 7), tp: 'Reel', n: 'Transformação do espaço',            s: s( 7) },
  { i: 132, c: 'Magia dos Temáticos', dt: d(12), tp: 'Reel', n: 'Tour: festa temática',               s: s(12) },
  { i: 133, c: 'Magia dos Temáticos', dt: d(17), tp: 'Reel', n: 'Depoimento de cliente',              s: s(17) },
  { i: 134, c: 'Magia dos Temáticos', dt: d(22), tp: 'Reel', n: 'Bastidores da montagem',             s: s(22) },
  { i: 135, c: 'Magia dos Temáticos', dt: d(27), tp: 'Reel', n: 'Festa dos sonhos',                   s: s(27) },
  { i: 136, c: 'Magia dos Temáticos', dt: d(31), tp: 'Reel', n: 'Decoração de aniversário',           s: s(31) },

  // ── Padaria R.A ── 4 Posts · 4 Reels ────────────────
  { i: 137, c: 'Padaria R.A', dt: d( 3), tp: 'Post', n: 'Pão artesanal do dia',                      s: s( 3) },
  { i: 138, c: 'Padaria R.A', dt: d(10), tp: 'Post', n: 'Encomende seu bolo',                         s: s(10) },
  { i: 139, c: 'Padaria R.A', dt: d(19), tp: 'Post', n: 'Novidade da semana',                         s: s(19) },
  { i: 140, c: 'Padaria R.A', dt: d(26), tp: 'Post', n: 'Salgados para eventos',                      s: s(26) },
  { i: 141, c: 'Padaria R.A', dt: d( 6), tp: 'Reel', n: 'Como fazemos nossos pães',                   s: s( 6) },
  { i: 142, c: 'Padaria R.A', dt: d(14), tp: 'Reel', n: 'Produção matinal',                           s: s(14) },
  { i: 143, c: 'Padaria R.A', dt: d(22), tp: 'Reel', n: 'Bolos personalizados',                       s: s(22) },
  { i: 144, c: 'Padaria R.A', dt: d(29), tp: 'Reel', n: 'Salgados artesanais',                        s: s(29) },

  // ── Pousada Dukuka ── 6 Posts · 12 Reels ────────────
  { i: 145, c: 'Pousada Dukuka', dt: d( 4), tp: 'Post', n: 'Check-in dos sonhos',                    s: s( 4) },
  { i: 146, c: 'Pousada Dukuka', dt: d( 8), tp: 'Post', n: 'Reserve sua hospedagem',                 s: s( 8) },
  { i: 147, c: 'Pousada Dukuka', dt: d(13), tp: 'Post', n: 'Café da manhã especial',                 s: s(13) },
  { i: 148, c: 'Pousada Dukuka', dt: d(18), tp: 'Post', n: 'Piscina e lazer',                        s: s(18) },
  { i: 149, c: 'Pousada Dukuka', dt: d(24), tp: 'Post', n: 'Pacote fim de semana',                   s: s(24) },
  { i: 150, c: 'Pousada Dukuka', dt: d(29), tp: 'Post', n: 'Aproveite o feriado',                    s: s(29) },
  { i: 151, c: 'Pousada Dukuka', dt: d( 1), tp: 'Reel', n: 'Tour pela pousada',                      s: s( 1) },
  { i: 152, c: 'Pousada Dukuka', dt: d( 5), tp: 'Reel', n: 'Quarto deluxe',                          s: s( 5) },
  { i: 153, c: 'Pousada Dukuka', dt: d( 9), tp: 'Reel', n: 'Área de lazer completa',                 s: s( 9) },
  { i: 154, c: 'Pousada Dukuka', dt: d(12), tp: 'Reel', n: 'Café da manhã incrível',                 s: s(12) },
  { i: 155, c: 'Pousada Dukuka', dt: d(16), tp: 'Reel', n: 'Piscina e relax',                        s: s(16) },
  { i: 156, c: 'Pousada Dukuka', dt: d(20), tp: 'Reel', n: 'Natureza ao redor',                      s: s(20) },
  { i: 157, c: 'Pousada Dukuka', dt: d(22), tp: 'Reel', n: 'Experiência dos hóspedes',               s: s(22) },
  { i: 158, c: 'Pousada Dukuka', dt: d(25), tp: 'Reel', n: 'Passeios pela região',                   s: s(25) },
  { i: 159, c: 'Pousada Dukuka', dt: d(27), tp: 'Reel', n: 'Trilhas disponíveis',                    s: s(27) },
  { i: 160, c: 'Pousada Dukuka', dt: d(28), tp: 'Reel', n: 'Jardim da pousada',                      s: s(28) },
  { i: 161, c: 'Pousada Dukuka', dt: d(30), tp: 'Reel', n: 'Pôr do sol na pousada',                  s: s(30) },
  { i: 162, c: 'Pousada Dukuka', dt: d(31), tp: 'Reel', n: 'Fim de semana perfeito',                 s: s(31) },

  // ── Quero Bolo ── 4 Posts · 4 Reels ─────────────────
  { i: 163, c: 'Quero Bolo', dt: d( 5), tp: 'Post', n: 'Bolo do mês',                                s: s( 5) },
  { i: 164, c: 'Quero Bolo', dt: d(12), tp: 'Post', n: 'Encomendas abertas',                          s: s(12) },
  { i: 165, c: 'Quero Bolo', dt: d(19), tp: 'Post', n: 'Sabor especial',                              s: s(19) },
  { i: 166, c: 'Quero Bolo', dt: d(26), tp: 'Post', n: 'Decoração personalizada',                     s: s(26) },
  { i: 167, c: 'Quero Bolo', dt: d( 8), tp: 'Reel', n: 'Como fazemos seu bolo',                       s: s( 8) },
  { i: 168, c: 'Quero Bolo', dt: d(15), tp: 'Reel', n: 'Decoração ao vivo',                           s: s(15) },
  { i: 169, c: 'Quero Bolo', dt: d(22), tp: 'Reel', n: 'Bolo Dia dos Namorados',                      s: s(22) },
  { i: 170, c: 'Quero Bolo', dt: d(29), tp: 'Reel', n: 'Escolha seu sabor',                           s: s(29) },

  // ── ViniPlas ── 8 Posts · 8 Reels ───────────────────
  { i: 171, c: 'ViniPlas', dt: d( 2), tp: 'Post', n: 'Produto em destaque',                           s: s( 2) },
  { i: 172, c: 'ViniPlas', dt: d( 6), tp: 'Post', n: 'Aplicação de vinil',                            s: s( 6) },
  { i: 173, c: 'ViniPlas', dt: d(10), tp: 'Post', n: 'Soluções em plástico',                          s: s(10) },
  { i: 174, c: 'ViniPlas', dt: d(14), tp: 'Post', n: 'Personalização para empresas',                  s: s(14) },
  { i: 175, c: 'ViniPlas', dt: d(18), tp: 'Post', n: 'Novidade na linha',                             s: s(18) },
  { i: 176, c: 'ViniPlas', dt: d(22), tp: 'Post', n: 'Qualidade garantida',                           s: s(22) },
  { i: 177, c: 'ViniPlas', dt: d(26), tp: 'Post', n: 'Orçamento rápido',                              s: s(26) },
  { i: 178, c: 'ViniPlas', dt: d(30), tp: 'Post', n: 'Projeto especial',                              s: s(30) },
  { i: 179, c: 'ViniPlas', dt: d( 4), tp: 'Reel', n: 'Aplicação de adesivo',                          s: s( 4) },
  { i: 180, c: 'ViniPlas', dt: d( 8), tp: 'Reel', n: 'Processo de produção',                          s: s( 8) },
  { i: 181, c: 'ViniPlas', dt: d(12), tp: 'Reel', n: 'Antes e depois',                                s: s(12) },
  { i: 182, c: 'ViniPlas', dt: d(16), tp: 'Reel', n: 'Personalização de frota',                       s: s(16) },
  { i: 183, c: 'ViniPlas', dt: d(20), tp: 'Reel', n: 'Tour pela fábrica',                             s: s(20) },
  { i: 184, c: 'ViniPlas', dt: d(24), tp: 'Reel', n: 'Produto mais vendido',                          s: s(24) },
  { i: 185, c: 'ViniPlas', dt: d(28), tp: 'Reel', n: 'Impressão digital',                             s: s(28) },
  { i: 186, c: 'ViniPlas', dt: d(31), tp: 'Reel', n: 'Resultado final',                               s: s(31) },

  // ── Rosângela Varas ── 6 Posts · 6 Reels ────────────
  { i: 187, c: 'Rosângela Varas', dt: d( 3), tp: 'Post', n: 'Dica da semana',                        s: s( 3) },
  { i: 188, c: 'Rosângela Varas', dt: d( 8), tp: 'Post', n: 'Novo projeto',                           s: s( 8) },
  { i: 189, c: 'Rosângela Varas', dt: d(14), tp: 'Post', n: 'Consultoria especial',                   s: s(14) },
  { i: 190, c: 'Rosângela Varas', dt: d(20), tp: 'Post', n: 'Resultado de cliente',                   s: s(20) },
  { i: 191, c: 'Rosângela Varas', dt: d(25), tp: 'Post', n: 'Minha rotina',                           s: s(25) },
  { i: 192, c: 'Rosângela Varas', dt: d(30), tp: 'Post', n: 'Oportunidade especial',                  s: s(30) },
  { i: 193, c: 'Rosângela Varas', dt: d( 5), tp: 'Reel', n: 'Minha história',                        s: s( 5) },
  { i: 194, c: 'Rosângela Varas', dt: d(11), tp: 'Reel', n: 'Dicas rápidas',                         s: s(11) },
  { i: 195, c: 'Rosângela Varas', dt: d(17), tp: 'Reel', n: 'Rotina de trabalho',                    s: s(17) },
  { i: 196, c: 'Rosângela Varas', dt: d(22), tp: 'Reel', n: 'Transformação do cliente',              s: s(22) },
  { i: 197, c: 'Rosângela Varas', dt: d(27), tp: 'Reel', n: 'Bastidores',                            s: s(27) },
  { i: 198, c: 'Rosângela Varas', dt: d(31), tp: 'Reel', n: 'Novidade especial',                     s: s(31) },

  // ── Compostela ── 8 Posts · 8 Reels ─────────────────
  { i: 199, c: 'Compostela', dt: d( 1), tp: 'Post', n: 'Menu do dia',                                 s: s( 1) },
  { i: 200, c: 'Compostela', dt: d( 5), tp: 'Post', n: 'Ambiente especial',                           s: s( 5) },
  { i: 201, c: 'Compostela', dt: d( 9), tp: 'Post', n: 'Reserve sua mesa',                            s: s( 9) },
  { i: 202, c: 'Compostela', dt: d(13), tp: 'Post', n: 'Experiência gastronômica',                    s: s(13) },
  { i: 203, c: 'Compostela', dt: d(17), tp: 'Post', n: 'Novidade no cardápio',                        s: s(17) },
  { i: 204, c: 'Compostela', dt: d(21), tp: 'Post', n: 'Destaque do mês',                             s: s(21) },
  { i: 205, c: 'Compostela', dt: d(25), tp: 'Post', n: 'Promoção especial',                           s: s(25) },
  { i: 206, c: 'Compostela', dt: d(29), tp: 'Post', n: 'Grupo e eventos',                             s: s(29) },
  { i: 207, c: 'Compostela', dt: d( 3), tp: 'Reel', n: 'Tour pelo espaço',                            s: s( 3) },
  { i: 208, c: 'Compostela', dt: d( 7), tp: 'Reel', n: 'Preparo dos pratos',                          s: s( 7) },
  { i: 209, c: 'Compostela', dt: d(11), tp: 'Reel', n: 'Experiência dos clientes',                    s: s(11) },
  { i: 210, c: 'Compostela', dt: d(15), tp: 'Reel', n: 'Cardápio em destaque',                        s: s(15) },
  { i: 211, c: 'Compostela', dt: d(19), tp: 'Reel', n: 'Como chegar',                                 s: s(19) },
  { i: 212, c: 'Compostela', dt: d(23), tp: 'Reel', n: 'Especial do chef',                            s: s(23) },
  { i: 213, c: 'Compostela', dt: d(27), tp: 'Reel', n: 'Noite especial',                              s: s(27) },
  { i: 214, c: 'Compostela', dt: d(31), tp: 'Reel', n: 'Ambiente rústico e aconchegante',             s: s(31) },

  // ── Suh Maya ── 4 Posts · 8 Reels ───────────────────
  { i: 215, c: 'Suh Maya', dt: d( 4), tp: 'Post', n: 'Show do fim de semana',                         s: s( 4) },
  { i: 216, c: 'Suh Maya', dt: d(11), tp: 'Post', n: 'Próxima apresentação',                          s: s(11) },
  { i: 217, c: 'Suh Maya', dt: d(18), tp: 'Post', n: 'Dica musical',                                  s: s(18) },
  { i: 218, c: 'Suh Maya', dt: d(26), tp: 'Post', n: 'Bastidores',                                    s: s(26) },
  { i: 219, c: 'Suh Maya', dt: d( 2), tp: 'Reel', n: 'Cover da semana',                               s: s( 2) },
  { i: 220, c: 'Suh Maya', dt: d( 6), tp: 'Reel', n: 'Apresentação ao vivo',                          s: s( 6) },
  { i: 221, c: 'Suh Maya', dt: d( 9), tp: 'Reel', n: 'Bastidores do show',                            s: s( 9) },
  { i: 222, c: 'Suh Maya', dt: d(13), tp: 'Reel', n: 'Nova música',                                   s: s(13) },
  { i: 223, c: 'Suh Maya', dt: d(17), tp: 'Reel', n: 'Tour pela agenda',                              s: s(17) },
  { i: 224, c: 'Suh Maya', dt: d(21), tp: 'Reel', n: 'Dica de voz',                                   s: s(21) },
  { i: 225, c: 'Suh Maya', dt: d(24), tp: 'Reel', n: 'Momentos do show',                              s: s(24) },
  { i: 226, c: 'Suh Maya', dt: d(28), tp: 'Reel', n: 'Ensaio musical',                                s: s(28) },
]
