import type { Client, ContentItem } from './types'

export const CLIENTS: Client[] = [
  { name: 'Casa de Ração 2 Irmãos',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Pet Shop'      },
  { name: 'Chalés Alto da Represa',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Hospedagem'    },
  { name: "Frango d'Água",           postsPerMonth: 8,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Restaurante'   },
  { name: 'Hidro Elétrica Andrade',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Energia'       },
  { name: 'Home Elevadores',         postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Elevadores'    },
  { name: 'Kátia Bigatello',         postsPerMonth: 12, reelsPerMonth: 12, nicho: 'variados',     subnicho: 'Estética'      },
  { name: 'Lareiras Grill',          postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Churrascaria'  },
  { name: 'Luthita',                 postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Serviços'      },
  { name: 'LuzioPan',                postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Panificadora'  },
  { name: 'Magia dos Temáticos',     postsPerMonth: 6,  reelsPerMonth: 6,  nicho: 'variados',     subnicho: 'Festas'        },
  { name: 'Padaria R.A',             postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Padaria'       },
  { name: 'Pousada Dukuka',          postsPerMonth: 6,  reelsPerMonth: 12, nicho: 'variados',     subnicho: 'Hospedagem'    },
  { name: 'Quero Bolo',              postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Confeitaria'   },
  { name: 'ViniPlas',                postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Plásticos'     },
  { name: 'Rosângela Varas',         postsPerMonth: 6,  reelsPerMonth: 6,  nicho: 'variados',     subnicho: 'Imóveis'       },
  { name: 'Compostela',              postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Restaurante'   },
  { name: 'Suh Maya',                postsPerMonth: 4,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Moda & Estilo' },
]

// Junho 2026 — alterar BASE_DATE e DATA para cada novo mês
export const BASE_DATE = new Date(2026, 5, 1)

const d = (day: number) => new Date(2026, 5, day)

// status automático: tudo pendente ao iniciar o mês
const s = (_day: number): 0 | 1 | 2 | 3 => 0

export const DATA: ContentItem[] = [

  // ── Casa de Ração 2 Irmãos ── 4 Posts · 4 Reels ─────
  { i: 1001, c: 'Casa de Ração 2 Irmãos', dt: d( 3), tp: 'Post', n: 'Pets no inverno: cuidados essenciais',   s: s( 3) },
  { i: 1002, c: 'Casa de Ração 2 Irmãos', dt: d(10), tp: 'Post', n: 'Ração premium em promoção de junho',     s: s(10) },
  { i: 1003, c: 'Casa de Ração 2 Irmãos', dt: d(17), tp: 'Post', n: 'Festa Junina com seu pet',               s: s(17) },
  { i: 1004, c: 'Casa de Ração 2 Irmãos', dt: d(24), tp: 'Post', n: 'Novidades na loja — inverno',            s: s(24) },
  { i: 1005, c: 'Casa de Ração 2 Irmãos', dt: d( 6), tp: 'Reel', n: 'Pets mais fofos da semana',              s: s( 6) },
  { i: 1006, c: 'Casa de Ração 2 Irmãos', dt: d(12), tp: 'Reel', n: 'Dia dos Namorados — pet como presente', s: s(12) },
  { i: 1007, c: 'Casa de Ração 2 Irmãos', dt: d(20), tp: 'Reel', n: 'Quadrilha de pets junina',               s: s(20) },
  { i: 1008, c: 'Casa de Ração 2 Irmãos', dt: d(27), tp: 'Reel', n: 'Como cuidar do pet no frio',             s: s(27) },

  // ── Chalés Alto da Represa ── 4 Posts · 4 Reels ─────
  { i: 1009, c: 'Chalés Alto da Represa', dt: d( 2), tp: 'Post', n: 'Inverno no chalé: temporada aconchegante', s: s( 2) },
  { i: 1010, c: 'Chalés Alto da Represa', dt: d( 9), tp: 'Post', n: 'Pacote especial — Dia dos Namorados',    s: s( 9) },
  { i: 1011, c: 'Chalés Alto da Represa', dt: d(16), tp: 'Post', n: 'Festa Junina na represa',                s: s(16) },
  { i: 1012, c: 'Chalés Alto da Represa', dt: d(23), tp: 'Post', n: 'Reserve para as férias de julho!',       s: s(23) },
  { i: 1013, c: 'Chalés Alto da Represa', dt: d( 5), tp: 'Reel', n: 'Tour pelos chalés no inverno',           s: s( 5) },
  { i: 1014, c: 'Chalés Alto da Represa', dt: d(12), tp: 'Reel', n: 'Surpresa de Dia dos Namorados na represa', s: s(12) },
  { i: 1015, c: 'Chalés Alto da Represa', dt: d(19), tp: 'Reel', n: 'Festa Junina na pousada',                s: s(19) },
  { i: 1016, c: 'Chalés Alto da Represa', dt: d(26), tp: 'Reel', n: 'Atividades especiais de férias',         s: s(26) },

  // ── Frango d'Água ── 8 Posts · 4 Reels ──────────────
  { i: 1017, c: "Frango d'Água", dt: d( 2), tp: 'Post', n: 'Cardápio especial de junho',                     s: s( 2) },
  { i: 1018, c: "Frango d'Água", dt: d( 5), tp: 'Post', n: 'Combo para o Dia dos Namorados',                 s: s( 5) },
  { i: 1019, c: "Frango d'Água", dt: d( 9), tp: 'Post', n: 'Promoção almoço executivo',                      s: s( 9) },
  { i: 1020, c: "Frango d'Água", dt: d(12), tp: 'Post', n: 'Jantar especial — Dia dos Namorados',            s: s(12) },
  { i: 1021, c: "Frango d'Água", dt: d(16), tp: 'Post', n: 'Pratos juninos no cardápio',                     s: s(16) },
  { i: 1022, c: "Frango d'Água", dt: d(20), tp: 'Post', n: 'Prato quentinho pro inverno',                    s: s(20) },
  { i: 1023, c: "Frango d'Água", dt: d(24), tp: 'Post', n: 'São João — pratos típicos',                      s: s(24) },
  { i: 1024, c: "Frango d'Água", dt: d(28), tp: 'Post', n: 'Férias de julho — venha jantar',                 s: s(28) },
  { i: 1025, c: "Frango d'Água", dt: d( 7), tp: 'Reel', n: 'Preparo do frango especial de junho',            s: s( 7) },
  { i: 1026, c: "Frango d'Água", dt: d(14), tp: 'Reel', n: 'Bastidores do jantar romântico',                 s: s(14) },
  { i: 1027, c: "Frango d'Água", dt: d(21), tp: 'Reel', n: 'Frango caipira — edição junina',                 s: s(21) },
  { i: 1028, c: "Frango d'Água", dt: d(28), tp: 'Reel', n: 'Tour pela nossa cozinha',                        s: s(28) },

  // ── Hidro Elétrica Andrade ── 4 Posts · 4 Reels ─────
  { i: 1029, c: 'Hidro Elétrica Andrade', dt: d( 3), tp: 'Post', n: 'Inverno e consumo de energia elétrica', s: s( 3) },
  { i: 1030, c: 'Hidro Elétrica Andrade', dt: d(10), tp: 'Post', n: 'Energia solar: economize no inverno',   s: s(10) },
  { i: 1031, c: 'Hidro Elétrica Andrade', dt: d(17), tp: 'Post', n: 'Projeto residencial concluído',         s: s(17) },
  { i: 1032, c: 'Hidro Elétrica Andrade', dt: d(24), tp: 'Post', n: 'Orçamento gratuito — junho',            s: s(24) },
  { i: 1033, c: 'Hidro Elétrica Andrade', dt: d( 7), tp: 'Reel', n: 'Nossa equipe em ação',                  s: s( 7) },
  { i: 1034, c: 'Hidro Elétrica Andrade', dt: d(14), tp: 'Reel', n: 'Antes e depois: instalação solar',      s: s(14) },
  { i: 1035, c: 'Hidro Elétrica Andrade', dt: d(21), tp: 'Reel', n: 'Dicas para reduzir a conta de luz',     s: s(21) },
  { i: 1036, c: 'Hidro Elétrica Andrade', dt: d(28), tp: 'Reel', n: 'Instalação completa em um dia',         s: s(28) },

  // ── Home Elevadores ── 8 Posts · 8 Reels ────────────
  { i: 1037, c: 'Home Elevadores', dt: d( 2), tp: 'Post', n: 'Elevador residencial: conforto no inverno',    s: s( 2) },
  { i: 1038, c: 'Home Elevadores', dt: d( 5), tp: 'Post', n: 'Dia dos Namorados — presente especial',        s: s( 5) },
  { i: 1039, c: 'Home Elevadores', dt: d( 9), tp: 'Post', n: 'Modelos compactos para sua casa',              s: s( 9) },
  { i: 1040, c: 'Home Elevadores', dt: d(13), tp: 'Post', n: 'Instalação sem quebra-quebra',                 s: s(13) },
  { i: 1041, c: 'Home Elevadores', dt: d(17), tp: 'Post', n: 'Manutenção preventiva de inverno',             s: s(17) },
  { i: 1042, c: 'Home Elevadores', dt: d(21), tp: 'Post', n: 'Planeje sua obra nas férias de julho',         s: s(21) },
  { i: 1043, c: 'Home Elevadores', dt: d(25), tp: 'Post', n: 'Consultoria gratuita em junho',                s: s(25) },
  { i: 1044, c: 'Home Elevadores', dt: d(29), tp: 'Post', n: 'Tecnologia e acessibilidade',                  s: s(29) },
  { i: 1045, c: 'Home Elevadores', dt: d( 3), tp: 'Reel', n: 'Como funciona nosso elevador',                 s: s( 3) },
  { i: 1046, c: 'Home Elevadores', dt: d( 7), tp: 'Reel', n: 'Instalação residencial ao vivo',               s: s( 7) },
  { i: 1047, c: 'Home Elevadores', dt: d(11), tp: 'Reel', n: 'Modelos disponíveis 2026',                     s: s(11) },
  { i: 1048, c: 'Home Elevadores', dt: d(15), tp: 'Reel', n: 'Depoimento de cliente satisfeito',             s: s(15) },
  { i: 1049, c: 'Home Elevadores', dt: d(19), tp: 'Reel', n: 'Antes e depois da instalação',                 s: s(19) },
  { i: 1050, c: 'Home Elevadores', dt: d(23), tp: 'Reel', n: 'Tour: elevador panorâmico',                    s: s(23) },
  { i: 1051, c: 'Home Elevadores', dt: d(27), tp: 'Reel', n: 'Processo de instalação completo',              s: s(27) },
  { i: 1052, c: 'Home Elevadores', dt: d(30), tp: 'Reel', n: 'Benefícios para sua qualidade de vida',        s: s(30) },

  // ── Kátia Bigatello ── 12 Posts · 12 Reels ──────────
  { i: 1053, c: 'Kátia Bigatello', dt: d( 1), tp: 'Post', n: 'Make especial para Dia dos Namorados',         s: s( 1) },
  { i: 1054, c: 'Kátia Bigatello', dt: d( 3), tp: 'Post', n: 'Make de inverno: cores quentes',               s: s( 3) },
  { i: 1055, c: 'Kátia Bigatello', dt: d( 6), tp: 'Post', n: 'Tutorial lábios perfeitos no frio',            s: s( 6) },
  { i: 1056, c: 'Kátia Bigatello', dt: d( 9), tp: 'Post', n: 'Look para festa junina',                       s: s( 9) },
  { i: 1057, c: 'Kátia Bigatello', dt: d(12), tp: 'Post', n: 'Make romântica — Dia dos Namorados',           s: s(12) },
  { i: 1058, c: 'Kátia Bigatello', dt: d(15), tp: 'Post', n: 'Cuidados com a pele no frio',                  s: s(15) },
  { i: 1059, c: 'Kátia Bigatello', dt: d(17), tp: 'Post', n: 'Make estilo country junino',                   s: s(17) },
  { i: 1060, c: 'Kátia Bigatello', dt: d(20), tp: 'Post', n: 'Tendências de beleza no inverno',              s: s(20) },
  { i: 1061, c: 'Kátia Bigatello', dt: d(22), tp: 'Post', n: 'Make simples para o dia a dia',                s: s(22) },
  { i: 1062, c: 'Kátia Bigatello', dt: d(25), tp: 'Post', n: 'Cores da temporada junina',                    s: s(25) },
  { i: 1063, c: 'Kátia Bigatello', dt: d(27), tp: 'Post', n: 'Make para formatura de julho',                 s: s(27) },
  { i: 1064, c: 'Kátia Bigatello', dt: d(30), tp: 'Post', n: 'Fechamento de junho: melhores looks',          s: s(30) },
  { i: 1065, c: 'Kátia Bigatello', dt: d( 2), tp: 'Reel', n: 'Tutorial: make romântica',                     s: s( 2) },
  { i: 1066, c: 'Kátia Bigatello', dt: d( 4), tp: 'Reel', n: 'Transformação para o Dia dos Namorados',      s: s( 4) },
  { i: 1067, c: 'Kátia Bigatello', dt: d( 7), tp: 'Reel', n: 'Preparação da pele no inverno',               s: s( 7) },
  { i: 1068, c: 'Kátia Bigatello', dt: d(10), tp: 'Reel', n: 'Make para festa junina',                       s: s(10) },
  { i: 1069, c: 'Kátia Bigatello', dt: d(13), tp: 'Reel', n: 'Produtos que uso todo dia',                    s: s(13) },
  { i: 1070, c: 'Kátia Bigatello', dt: d(16), tp: 'Reel', n: 'Tutorial lábios nude para o frio',             s: s(16) },
  { i: 1071, c: 'Kátia Bigatello', dt: d(19), tp: 'Reel', n: 'Make estilo country/junino',                   s: s(19) },
  { i: 1072, c: 'Kátia Bigatello', dt: d(21), tp: 'Reel', n: 'Correção de imperfeições',                     s: s(21) },
  { i: 1073, c: 'Kátia Bigatello', dt: d(24), tp: 'Reel', n: '5 dicas de make para festas juninas',          s: s(24) },
  { i: 1074, c: 'Kátia Bigatello', dt: d(26), tp: 'Reel', n: 'Blush placement para o inverno',               s: s(26) },
  { i: 1075, c: 'Kátia Bigatello', dt: d(28), tp: 'Reel', n: 'Make para formatura',                          s: s(28) },
  { i: 1076, c: 'Kátia Bigatello', dt: d(30), tp: 'Reel', n: 'Rotina de cuidados no frio',                   s: s(30) },

  // ── Lareiras Grill ── 8 Posts · 8 Reels ─────────────
  { i: 1077, c: 'Lareiras Grill', dt: d( 2), tp: 'Post', n: 'Destaque do fim de semana',                     s: s( 2) },
  { i: 1078, c: 'Lareiras Grill', dt: d( 5), tp: 'Post', n: 'Fondue especial do inverno',                    s: s( 5) },
  { i: 1079, c: 'Lareiras Grill', dt: d( 8), tp: 'Post', n: 'Cardápio de inverno — novidades',               s: s( 8) },
  { i: 1080, c: 'Lareiras Grill', dt: d(12), tp: 'Post', n: 'Jantar especial Dia dos Namorados',             s: s(12) },
  { i: 1081, c: 'Lareiras Grill', dt: d(16), tp: 'Post', n: 'Arroz de leite caramelado',                     s: s(16) },
  { i: 1082, c: 'Lareiras Grill', dt: d(19), tp: 'Post', n: 'Festa Junina — pratos típicos',                 s: s(19) },
  { i: 1083, c: 'Lareiras Grill', dt: d(23), tp: 'Post', n: 'São João — ceia especial',                      s: s(23) },
  { i: 1084, c: 'Lareiras Grill', dt: d(26), tp: 'Post', n: 'Encerramento de junho',                         s: s(26) },
  { i: 1085, c: 'Lareiras Grill', dt: d( 3), tp: 'Reel', n: 'Tour pelo restaurante no inverno',              s: s( 3) },
  { i: 1086, c: 'Lareiras Grill', dt: d( 7), tp: 'Reel', n: 'Lareiras Grill — ambiente aconchegante',        s: s( 7) },
  { i: 1087, c: 'Lareiras Grill', dt: d(10), tp: 'Reel', n: 'Meme do inverno',                               s: s(10) },
  { i: 1088, c: 'Lareiras Grill', dt: d(14), tp: 'Reel', n: 'À la carte especial de junho',                  s: s(14) },
  { i: 1089, c: 'Lareiras Grill', dt: d(17), tp: 'Reel', n: 'Feedback de clientes',                          s: s(17) },
  { i: 1090, c: 'Lareiras Grill', dt: d(20), tp: 'Reel', n: 'Especial junino',                               s: s(20) },
  { i: 1091, c: 'Lareiras Grill', dt: d(24), tp: 'Reel', n: 'Influencer kerges na quadrilha',                s: s(24) },
  { i: 1092, c: 'Lareiras Grill', dt: d(27), tp: 'Reel', n: 'Meme sem 1 real no São João',                   s: s(27) },

  // ── Luthita ── 8 Posts · 8 Reels ────────────────────
  { i: 1093, c: 'Luthita', dt: d( 1), tp: 'Post', n: 'Lookbook de inverno',                                  s: s( 1) },
  { i: 1094, c: 'Luthita', dt: d( 5), tp: 'Post', n: 'Novidade na coleção de frio',                          s: s( 5) },
  { i: 1095, c: 'Luthita', dt: d( 8), tp: 'Post', n: 'Look para festa junina',                               s: s( 8) },
  { i: 1096, c: 'Luthita', dt: d(12), tp: 'Post', n: 'Estilo para o Dia dos Namorados',                      s: s(12) },
  { i: 1097, c: 'Luthita', dt: d(16), tp: 'Post', n: 'Peças de inverno em destaque',                         s: s(16) },
  { i: 1098, c: 'Luthita', dt: d(20), tp: 'Post', n: 'Look casual aconchegante',                             s: s(20) },
  { i: 1099, c: 'Luthita', dt: d(24), tp: 'Post', n: 'Estilo arraiá — looks juninos',                        s: s(24) },
  { i: 1100, c: 'Luthita', dt: d(28), tp: 'Post', n: 'Peças da coleção de férias',                           s: s(28) },
  { i: 1101, c: 'Luthita', dt: d( 3), tp: 'Reel', n: 'Unboxing coleção de inverno',                          s: s( 3) },
  { i: 1102, c: 'Luthita', dt: d( 6), tp: 'Reel', n: 'Como usar casacos e sobreposições',                    s: s( 6) },
  { i: 1103, c: 'Luthita', dt: d(10), tp: 'Reel', n: 'Look do dia para o frio',                              s: s(10) },
  { i: 1104, c: 'Luthita', dt: d(14), tp: 'Reel', n: 'Styling tips — Dia dos Namorados',                     s: s(14) },
  { i: 1105, c: 'Luthita', dt: d(18), tp: 'Reel', n: 'Novidades de inverno chegando',                        s: s(18) },
  { i: 1106, c: 'Luthita', dt: d(22), tp: 'Reel', n: 'Haul de roupas de frio',                               s: s(22) },
  { i: 1107, c: 'Luthita', dt: d(26), tp: 'Reel', n: '5 looks para festa junina',                            s: s(26) },
  { i: 1108, c: 'Luthita', dt: d(30), tp: 'Reel', n: 'Looks para as férias de julho',                        s: s(30) },

  // ── LuzioPan ── 8 Posts · 8 Reels ───────────────────
  { i: 1109, c: 'LuzioPan', dt: d( 4), tp: 'Post', n: 'Cuca de festa junina com Prodipanni',                s: s( 4) },
  { i: 1110, c: 'LuzioPan', dt: d( 7), tp: 'Post', n: 'Macarrão para a ceia junina',                        s: s( 7) },
  { i: 1111, c: 'LuzioPan', dt: d(11), tp: 'Post', n: 'Prodipanni no cardápio de inverno',                  s: s(11) },
  { i: 1112, c: 'LuzioPan', dt: d(14), tp: 'Post', n: 'Bolo de milho com Prodipanni',                       s: s(14) },
  { i: 1113, c: 'LuzioPan', dt: d(18), tp: 'Post', n: 'Junho é o mês de vender mais',                       s: s(18) },
  { i: 1114, c: 'LuzioPan', dt: d(21), tp: 'Post', n: 'DONO DE PADARIA — especial São João',                s: s(21) },
  { i: 1115, c: 'LuzioPan', dt: d(25), tp: 'Post', n: 'Venda mais com o Prodipanni no arraiá',              s: s(25) },
  { i: 1116, c: 'LuzioPan', dt: d(28), tp: 'Post', n: 'Desenforme perfeito para festas juninas',            s: s(28) },
  { i: 1117, c: 'LuzioPan', dt: d( 2), tp: 'Reel', n: 'Para quem é o Prodipanni',                           s: s( 2) },
  { i: 1118, c: 'LuzioPan', dt: d( 5), tp: 'Reel', n: 'Quem é o Luzio — especial junho',                   s: s( 5) },
  { i: 1119, c: 'LuzioPan', dt: d( 9), tp: 'Reel', n: 'Prodipanni bolo de milho',                           s: s( 9) },
  { i: 1120, c: 'LuzioPan', dt: d(12), tp: 'Reel', n: 'Prodipanni cuca junina',                             s: s(12) },
  { i: 1121, c: 'LuzioPan', dt: d(16), tp: 'Reel', n: 'Prodipanni para festa junina',                       s: s(16) },
  { i: 1122, c: 'LuzioPan', dt: d(19), tp: 'Reel', n: 'Prodipanni paçoca cake',                             s: s(19) },
  { i: 1123, c: 'LuzioPan', dt: d(26), tp: 'Reel', n: 'MEME ARRAIÁ',                                        s: s(26) },
  { i: 1124, c: 'LuzioPan', dt: d(30), tp: 'Reel', n: 'Como fazer bolo de milho perfeito',                  s: s(30) },

  // ── Magia dos Temáticos ── 6 Posts · 6 Reels ────────
  { i: 1125, c: 'Magia dos Temáticos', dt: d( 7), tp: 'Post', n: 'Festa temática de São João',               s: s( 7) },
  { i: 1126, c: 'Magia dos Temáticos', dt: d(12), tp: 'Post', n: 'Festa especial Dia dos Namorados',         s: s(12) },
  { i: 1127, c: 'Magia dos Temáticos', dt: d(15), tp: 'Post', n: 'Reserve sua data para julho',              s: s(15) },
  { i: 1128, c: 'Magia dos Temáticos', dt: d(21), tp: 'Post', n: 'Festa junina completa — tudo incluso',     s: s(21) },
  { i: 1129, c: 'Magia dos Temáticos', dt: d(24), tp: 'Post', n: 'São João — decoração temática',            s: s(24) },
  { i: 1130, c: 'Magia dos Temáticos', dt: d(27), tp: 'Post', n: 'Pacote de festas para julho',              s: s(27) },
  { i: 1131, c: 'Magia dos Temáticos', dt: d( 2), tp: 'Reel', n: 'Conheça a Magia dos Temáticos',            s: s( 2) },
  { i: 1132, c: 'Magia dos Temáticos', dt: d( 4), tp: 'Reel', n: 'Não é só uma festa, é uma experiência',   s: s( 4) },
  { i: 1133, c: 'Magia dos Temáticos', dt: d( 8), tp: 'Reel', n: 'Meme: como organizar um arraiá',           s: s( 8) },
  { i: 1134, c: 'Magia dos Temáticos', dt: d(16), tp: 'Reel', n: 'Você nunca viu um arraiá assim',           s: s(16) },
  { i: 1135, c: 'Magia dos Temáticos', dt: d(20), tp: 'Reel', n: 'Bastidores da decoração junina',           s: s(20) },
  { i: 1136, c: 'Magia dos Temáticos', dt: d(28), tp: 'Reel', n: 'Festa de aniversário temática',            s: s(28) },

  // ── Padaria R.A ── 4 Posts · 4 Reels ────────────────
  { i: 1137, c: 'Padaria R.A', dt: d( 3), tp: 'Post', n: 'Cuca e paçoca — especial Festa Junina',           s: s( 3) },
  { i: 1138, c: 'Padaria R.A', dt: d(10), tp: 'Post', n: 'Bolo de milho especial',                           s: s(10) },
  { i: 1139, c: 'Padaria R.A', dt: d(17), tp: 'Post', n: 'Pão quentinho no frio',                            s: s(17) },
  { i: 1140, c: 'Padaria R.A', dt: d(24), tp: 'Post', n: 'Ceia de São João — encomendas abertas',            s: s(24) },
  { i: 1141, c: 'Padaria R.A', dt: d( 6), tp: 'Reel', n: 'Padaria R.A — especial inverno',                   s: s( 6) },
  { i: 1142, c: 'Padaria R.A', dt: d(14), tp: 'Reel', n: 'Delícias juninas na padaria',                      s: s(14) },
  { i: 1143, c: 'Padaria R.A', dt: d(20), tp: 'Reel', n: 'O café que você merece no frio',                   s: s(20) },
  { i: 1144, c: 'Padaria R.A', dt: d(27), tp: 'Reel', n: 'Vem tomar um quentão comigo',                      s: s(27) },

  // ── Pousada Dukuka ── 6 Posts · 12 Reels ────────────
  { i: 1145, c: 'Pousada Dukuka', dt: d( 4), tp: 'Post', n: 'Pacote especial de inverno',                   s: s( 4) },
  { i: 1146, c: 'Pousada Dukuka', dt: d( 8), tp: 'Post', n: 'Dia dos Namorados na pousada',                 s: s( 8) },
  { i: 1147, c: 'Pousada Dukuka', dt: d(13), tp: 'Post', n: 'Festa Junina na pousada',                      s: s(13) },
  { i: 1148, c: 'Pousada Dukuka', dt: d(18), tp: 'Post', n: 'Chalé aconchegante no frio',                   s: s(18) },
  { i: 1149, c: 'Pousada Dukuka', dt: d(24), tp: 'Post', n: 'São João — fogueira e quadrilha',              s: s(24) },
  { i: 1150, c: 'Pousada Dukuka', dt: d(29), tp: 'Post', n: 'Férias de julho — reserve já!',                s: s(29) },
  { i: 1151, c: 'Pousada Dukuka', dt: d( 1), tp: 'Reel', n: 'Tour pela pousada no inverno',                 s: s( 1) },
  { i: 1152, c: 'Pousada Dukuka', dt: d( 4), tp: 'Reel', n: 'Kaique influencer — especial junho',           s: s( 4) },
  { i: 1153, c: 'Pousada Dukuka', dt: d( 8), tp: 'Reel', n: 'Lareira e conforto no frio',                   s: s( 8) },
  { i: 1154, c: 'Pousada Dukuka', dt: d(12), tp: 'Reel', n: 'Surpresa de Dia dos Namorados',                s: s(12) },
  { i: 1155, c: 'Pousada Dukuka', dt: d(15), tp: 'Reel', n: 'Festa junina na pousada',                      s: s(15) },
  { i: 1156, c: 'Pousada Dukuka', dt: d(18), tp: 'Reel', n: 'Natureza no inverno',                          s: s(18) },
  { i: 1157, c: 'Pousada Dukuka', dt: d(20), tp: 'Reel', n: 'Depoimentos de casais',                        s: s(20) },
  { i: 1158, c: 'Pousada Dukuka', dt: d(22), tp: 'Reel', n: 'Passeios de inverno pela região',              s: s(22) },
  { i: 1159, c: 'Pousada Dukuka', dt: d(25), tp: 'Reel', n: 'Trilhas na serra em junho',                    s: s(25) },
  { i: 1160, c: 'Pousada Dukuka', dt: d(27), tp: 'Reel', n: 'Jardim da pousada florido',                    s: s(27) },
  { i: 1161, c: 'Pousada Dukuka', dt: d(29), tp: 'Reel', n: 'Pôr do sol de inverno na pousada',             s: s(29) },
  { i: 1162, c: 'Pousada Dukuka', dt: d(30), tp: 'Reel', n: 'Fim de semana perfeito no frio',               s: s(30) },

  // ── Quero Bolo ── 4 Posts · 4 Reels ─────────────────
  { i: 1163, c: 'Quero Bolo', dt: d( 5), tp: 'Post', n: 'Bolo de milho especial de junho',                  s: s( 5) },
  { i: 1164, c: 'Quero Bolo', dt: d(12), tp: 'Post', n: 'Bolo para o Dia dos Namorados',                    s: s(12) },
  { i: 1165, c: 'Quero Bolo', dt: d(19), tp: 'Post', n: 'Encomendas para festa junina',                     s: s(19) },
  { i: 1166, c: 'Quero Bolo', dt: d(26), tp: 'Post', n: 'Sabores de inverno — peça o seu',                  s: s(26) },
  { i: 1167, c: 'Quero Bolo', dt: d( 8), tp: 'Reel', n: 'Como fazemos o bolo de milho',                     s: s( 8) },
  { i: 1168, c: 'Quero Bolo', dt: d(15), tp: 'Reel', n: 'Decoração para festa junina',                      s: s(15) },
  { i: 1169, c: 'Quero Bolo', dt: d(22), tp: 'Reel', n: 'Bolo temático de arraiá',                          s: s(22) },
  { i: 1170, c: 'Quero Bolo', dt: d(29), tp: 'Reel', n: 'Escolha seu sabor para julho',                     s: s(29) },

  // ── ViniPlas ── 8 Posts · 8 Reels ───────────────────
  { i: 1171, c: 'ViniPlas', dt: d( 2), tp: 'Post', n: 'Adesivos decorativos para o arraiá',                 s: s( 2) },
  { i: 1172, c: 'ViniPlas', dt: d( 6), tp: 'Post', n: 'Personalização para o Dia dos Namorados',            s: s( 6) },
  { i: 1173, c: 'ViniPlas', dt: d(10), tp: 'Post', n: 'Vinil para fachadas e espaços',                      s: s(10) },
  { i: 1174, c: 'ViniPlas', dt: d(14), tp: 'Post', n: 'Soluções em plástico para eventos',                  s: s(14) },
  { i: 1175, c: 'ViniPlas', dt: d(18), tp: 'Post', n: 'Novidades da linha para julho',                      s: s(18) },
  { i: 1176, c: 'ViniPlas', dt: d(22), tp: 'Post', n: 'Qualidade garantida em cada projeto',                s: s(22) },
  { i: 1177, c: 'ViniPlas', dt: d(26), tp: 'Post', n: 'Orçamento expresso — sem burocracia',                s: s(26) },
  { i: 1178, c: 'ViniPlas', dt: d(30), tp: 'Post', n: 'Projeto especial de fim de mês',                     s: s(30) },
  { i: 1179, c: 'ViniPlas', dt: d( 4), tp: 'Reel', n: 'Aplicação de adesivo decorativo',                    s: s( 4) },
  { i: 1180, c: 'ViniPlas', dt: d( 8), tp: 'Reel', n: 'Processo de produção ao vivo',                       s: s( 8) },
  { i: 1181, c: 'ViniPlas', dt: d(12), tp: 'Reel', n: 'Antes e depois',                                     s: s(12) },
  { i: 1182, c: 'ViniPlas', dt: d(16), tp: 'Reel', n: 'Personalização para festa junina',                   s: s(16) },
  { i: 1183, c: 'ViniPlas', dt: d(20), tp: 'Reel', n: 'Tour pela fábrica',                                  s: s(20) },
  { i: 1184, c: 'ViniPlas', dt: d(24), tp: 'Reel', n: 'Produto mais vendido do mês',                        s: s(24) },
  { i: 1185, c: 'ViniPlas', dt: d(28), tp: 'Reel', n: 'Impressão digital de alta qualidade',                s: s(28) },
  { i: 1186, c: 'ViniPlas', dt: d(30), tp: 'Reel', n: 'Resultado final — cliente satisfeito',               s: s(30) },

  // ── Rosângela Varas ── 6 Posts · 6 Reels ────────────
  { i: 1187, c: 'Rosângela Varas', dt: d( 6), tp: 'Post', n: 'Dieta junina: armadilhas que você não vê',   s: s( 6) },
  { i: 1188, c: 'Rosângela Varas', dt: d(11), tp: 'Post', n: 'Saúde hormonal no inverno',                  s: s(11) },
  { i: 1189, c: 'Rosângela Varas', dt: d(16), tp: 'Post', n: 'Exercícios na estação fria',                 s: s(16) },
  { i: 1190, c: 'Rosângela Varas', dt: d(20), tp: 'Post', n: 'Como manter o peso nas festas juninas',      s: s(20) },
  { i: 1191, c: 'Rosângela Varas', dt: d(24), tp: 'Post', n: 'São João sem culpa: guia prático',           s: s(24) },
  { i: 1192, c: 'Rosângela Varas', dt: d(27), tp: 'Post', n: 'Cuide da sua saúde nas férias',              s: s(27) },
  { i: 1193, c: 'Rosângela Varas', dt: d( 5), tp: 'Reel', n: 'Efeitos do frio no metabolismo',            s: s( 5) },
  { i: 1194, c: 'Rosângela Varas', dt: d( 9), tp: 'Reel', n: 'Mais é claro — especial inverno',            s: s( 9) },
  { i: 1195, c: 'Rosângela Varas', dt: d(13), tp: 'Reel', n: 'Hormônios e clima',                          s: s(13) },
  { i: 1196, c: 'Rosângela Varas', dt: d(19), tp: 'Reel', n: 'Entrevista — perda de peso no inverno',      s: s(19) },
  { i: 1197, c: 'Rosângela Varas', dt: d(23), tp: 'Reel', n: 'Festa junina e saúde',                       s: s(23) },
  { i: 1198, c: 'Rosângela Varas', dt: d(25), tp: 'Reel', n: 'Institucional — junho',                      s: s(25) },

  // ── Compostela ── 8 Posts · 8 Reels ─────────────────
  { i: 1199, c: 'Compostela', dt: d( 1), tp: 'Post', n: 'Menu de inverno',                                  s: s( 1) },
  { i: 1200, c: 'Compostela', dt: d( 5), tp: 'Post', n: 'Ambiente especial no frio',                        s: s( 5) },
  { i: 1201, c: 'Compostela', dt: d( 9), tp: 'Post', n: 'Reserve sua mesa — Dia dos Namorados',             s: s( 9) },
  { i: 1202, c: 'Compostela', dt: d(13), tp: 'Post', n: 'Jantar especial 12 de junho',                      s: s(13) },
  { i: 1203, c: 'Compostela', dt: d(17), tp: 'Post', n: 'Novidade no cardápio junino',                      s: s(17) },
  { i: 1204, c: 'Compostela', dt: d(21), tp: 'Post', n: 'Destaque da semana',                               s: s(21) },
  { i: 1205, c: 'Compostela', dt: d(25), tp: 'Post', n: 'Promoção de fim de mês',                           s: s(25) },
  { i: 1206, c: 'Compostela', dt: d(29), tp: 'Post', n: 'Grupos e eventos para julho',                      s: s(29) },
  { i: 1207, c: 'Compostela', dt: d( 3), tp: 'Reel', n: 'Tour pelo espaço no inverno',                      s: s( 3) },
  { i: 1208, c: 'Compostela', dt: d( 7), tp: 'Reel', n: 'Preparo dos pratos especiais',                     s: s( 7) },
  { i: 1209, c: 'Compostela', dt: d(11), tp: 'Reel', n: 'Experiência dos clientes',                         s: s(11) },
  { i: 1210, c: 'Compostela', dt: d(15), tp: 'Reel', n: 'Cardápio de inverno em destaque',                  s: s(15) },
  { i: 1211, c: 'Compostela', dt: d(19), tp: 'Reel', n: 'Como chegar ao Compostela',                        s: s(19) },
  { i: 1212, c: 'Compostela', dt: d(23), tp: 'Reel', n: 'Especial do chef — São João',                      s: s(23) },
  { i: 1213, c: 'Compostela', dt: d(27), tp: 'Reel', n: 'Noite especial de festa junina',                   s: s(27) },
  { i: 1214, c: 'Compostela', dt: d(30), tp: 'Reel', n: 'Ambiente rústico e aconchegante',                  s: s(30) },

  // ── Suh Maya ── 4 Posts · 8 Reels ───────────────────
  { i: 1215, c: 'Suh Maya', dt: d( 4), tp: 'Post', n: 'Show especial de Festa Junina',                      s: s( 4) },
  { i: 1216, c: 'Suh Maya', dt: d(18), tp: 'Post', n: 'Dica musical para o São João',                       s: s(18) },
  { i: 1217, c: 'Suh Maya', dt: d(24), tp: 'Post', n: 'São João — ao vivo no arraiá',                       s: s(24) },
  { i: 1218, c: 'Suh Maya', dt: d(27), tp: 'Post', n: 'Bastidores do arraiá',                               s: s(27) },
  { i: 1219, c: 'Suh Maya', dt: d( 1), tp: 'Reel', n: 'De qual cidade você é',                              s: s( 1) },
  { i: 1220, c: 'Suh Maya', dt: d(11), tp: 'Reel', n: 'Agora que o forró começou',                          s: s(11) },
  { i: 1221, c: 'Suh Maya', dt: d(13), tp: 'Reel', n: 'Postando 10mil composições juninas',                 s: s(13) },
  { i: 1222, c: 'Suh Maya', dt: d(15), tp: 'Reel', n: 'TBT show de São João do ano passado',                s: s(15) },
  { i: 1223, c: 'Suh Maya', dt: d(17), tp: 'Reel', n: 'De qual cidade você é — v2',                         s: s(17) },
  { i: 1224, c: 'Suh Maya', dt: d(21), tp: 'Reel', n: 'Será... o papo que rola no arraiá',                  s: s(21) },
  { i: 1225, c: 'Suh Maya', dt: d(25), tp: 'Reel', n: 'Só quem não veio ao show',                           s: s(25) },
  { i: 1226, c: 'Suh Maya', dt: d(29), tp: 'Reel', n: 'Deixa eu cantar um forró',                           s: s(29) },
]
