import type { Client, ContentItem } from './types'

export const CLIENTS: Client[] = [
  { name: 'Casa de Ração 2 Irmãos',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Pet Shop'      },
  { name: 'Chalés Alto da Represa',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Hospedagem'    },
  { name: "Frango d'Água",           postsPerMonth: 8,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Restaurante'   },
  { name: 'Hidro Elétrica Andrade',  postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'variados',     subnicho: 'Energia'       },
  { name: 'Home Elevadores',         postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Elevadores'    },
  { name: 'Kátia Bigatello',         postsPerMonth: 12, reelsPerMonth: 12, nicho: 'variados',     subnicho: 'Estética'      },
  { name: 'Lareiras Grill',          postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Churrascaria'  },
  { name: 'Luthita',                 postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Serviços'      },
  { name: 'LuzioPan',                postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Panificadora'  },
  { name: 'Magia dos Temáticos',     postsPerMonth: 6,  reelsPerMonth: 6,  nicho: 'gastronomico', subnicho: 'Festas'        },
  { name: 'Padaria R.A',             postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Padaria'       },
  { name: 'Pousada Dukuka',          postsPerMonth: 6,  reelsPerMonth: 12, nicho: 'variados',     subnicho: 'Hospedagem'    },
  { name: 'Quero Bolo',              postsPerMonth: 4,  reelsPerMonth: 4,  nicho: 'gastronomico', subnicho: 'Confeitaria'   },
  { name: 'ViniPlas',                postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Plásticos'     },
  { name: 'Rosângela Varas',         postsPerMonth: 6,  reelsPerMonth: 6,  nicho: 'variados',     subnicho: 'Imóveis'       },
  { name: 'Compostela',              postsPerMonth: 8,  reelsPerMonth: 8,  nicho: 'gastronomico', subnicho: 'Restaurante'   },
  { name: 'Suh Maya',                postsPerMonth: 4,  reelsPerMonth: 8,  nicho: 'variados',     subnicho: 'Moda & Estilo' },
]

// Junho 2026 — alterar BASE_DATE e DATA para cada novo mês
export const BASE_DATE = new Date(2026, 5, 1)

const d = (day: number) => new Date(2026, 5, day)

// status automático: tudo pendente ao iniciar o mês
const s = (_day: number): 0 | 1 | 2 | 3 => 0

export const DATA: ContentItem[] = [

  // ── Casa de Ração 2 Irmãos ── 4 Posts · 4 Reels ─────
  { i: 1001, c: 'Casa de Ração 2 Irmãos', dt: d( 3), tp: 'Post', n: 'Pets no inverno: cuidados essenciais',   s: s( 3) },
  { i: 1002, c: 'Casa de Ração 2 Irmãos', dt: d(10), tp: 'Post', n: 'Ração premium em promoção de junho',     s: s(10) },
  { i: 1003, c: 'Casa de Ração 2 Irmãos', dt: d(17), tp: 'Post', n: 'Festa Junina com seu pet',               s: s(17) },
  { i: 1004, c: 'Casa de Ração 2 Irmãos', dt: d(24), tp: 'Post', n: 'Novidades na loja — inverno',            s: s(24) },
  { i: 1005, c: 'Casa de Ração 2 Irmãos', dt: d( 6), tp: 'Reel', n: 'Pets mais fofos da semana',              s: s( 6) },
  { i: 1006, c: 'Casa de Ração 2 Irmãos', dt: d(12), tp: 'Reel', n: 'Dia dos Namorados — pet como presente', s: s(12) },
  { i: 1007, c: 'Casa de Ração 2 Irmãos', dt: d(20), tp: 'Reel', n: 'Quadrilha de pets junina',               s: s(20) },
  { i: 1008, c: 'Casa de Ração 2 Irmãos', dt: d(27), tp: 'Reel', n: 'Como cuidar do pet no frio',             s: s(27) },

  // ── Chalés Alto da Represa ── 4 Posts · 4 Reels ─────
  { i: 1009, c: 'Chalés Alto da Represa', dt: d( 2), tp: 'Post', n: 'Inverno no chalé: temporada aconchegante', s: s( 2) },
  { i: 1010, c: 'Chalés Alto da Represa', dt: d( 9), tp: 'Post', n: 'Pacote especial — Dia dos Namorados',    s: s( 9) },
  { i: 1011, c: 'Chalés Alto da Represa', dt: d(16), tp: 'Post', n: 'Festa Junina na represa',                s: s(16) },
  { i: 1012, c: 'Chalés Alto da Represa', dt: d(23), tp: 'Post', n: 'Reserve para as férias de julho!',       s: s(23) },
  { i: 1013, c: 'Chalés Alto da Represa', dt: d( 5), tp: 'Reel', n: 'Tour pelos chalés no inverno',           s: s( 5) },
  { i: 1014, c: 'Chalés Alto da Represa', dt: d(12), tp: 'Reel', n: 'Surpresa de Dia dos Namorados na represa', s: s(12) },
  { i: 1015, c: 'Chalés Alto da Represa', dt: d(19), tp: 'Reel', n: 'Festa Junina na pousada',                s: s(19) },
  { i: 1016, c: 'Chalés Alto da Represa', dt: d(26), tp: 'Reel', n: 'Atividades especiais de férias',         s: s(26) },

  // ── Frango d'Água ── 8 Posts · 4 Reels ──────────────
  { i: 1017, c: "Frango d'Água", dt: d( 2), tp: 'Post', n: 'Cardápio especial de junho',                     s: s( 2) },
  { i: 1018, c: "Frango d'Água", dt: d( 5), tp: 'Post', n: 'Combo para o Dia dos Namorados',                 s: s( 5) },
  { i: 1019, c: "Frango d'Água", dt: d( 9), tp: 'Post', n: 'Promoção almoço executivo',                      s: s( 9) },
  { i: 1020, c: "Frango d'Água", dt: d(12), tp: 'Post', n: 'Jantar especial — Dia dos Namorados',            s: s(12) },
  { i: 1021, c: "Frango d'Água", dt: d(16), tp: 'Post', n: 'Pratos juninos no cardápio',                     s: s(16) },
  { i: 1022, c: "Frango d'Água", dt: d(20), tp: 'Post', n: 'Prato quentinho pro inverno',                    s: s(20) },
  { i: 1023, c: "Frango d'Água", dt: d(24), tp: 'Post', n: 'São João — pratos típicos',                      s: s(24) },
  { i: 1024, c: "Frango d'Água", dt: d(28), tp: 'Post', n: 'Férias de julho — venha jantar',                 s: s(28) },
  { i: 1025, c: "Frango d'Água", dt: d( 7), tp: 'Reel', n: 'Preparo do frango especial de junho',            s: s( 7) },
  { i: 1026, c: "Frango d'Água", dt: d(14), tp: 'Reel', n: 'Bastidores do jantar romântico',                 s: s(14) },
  { i: 1027, c: "Frango d'Água", dt: d(21), tp: 'Reel', n: 'Frango caipira — edição junina',                 s: s(21) },
  { i: 1028, c: "Frango d'Água", dt: d(28), tp: 'Reel', n: 'Tour pela nossa cozinha',                        s: s(28) },

  // ── Hidro Elétrica Andrade ── 4 Posts · 4 Reels ─────
  { i: 1029, c: 'Hidro Elétrica Andrade', dt: d( 3), tp: 'Post', n: 'Inverno e consumo de energia elétrica', s: s( 3) },
  { i: 1030, c: 'Hidro Elétrica Andrade', dt: d(10), tp: 'Post', n: 'Energia solar: economize no inverno',   s: s(10) },
  { i: 1031, c: 'Hidro Elétrica Andrade', dt: d(17), tp: 'Post', n: 'Projeto residencial concluído',         s: s(17) },
  { i: 1032, c: 'Hidro Elétrica Andrade', dt: d(24), tp: 'Post', n: 'Orçamento gratuito — junho',            s: s(24) },
  { i: 1033, c: 'Hidro Elétrica Andrade', dt: d( 7), tp: 'Reel', n: 'Nossa equipe em ação',                  s: s( 7) },
  { i: 1034, c: 'Hidro Elétrica Andrade', dt: d(14), tp: 'Reel', n: 'Antes e depois: instalação solar',      s: s(14) },
  { i: 1035, c: 'Hidro Elétrica Andrade', dt: d(21), tp: 'Reel', n: 'Dicas para reduzir a conta de luz',     s: s(21) },
  { i: 1036, c: 'Hidro Elétrica Andrade', dt: d(28), tp: 'Reel', n: 'Instalação completa em um dia',         s: s(28) },

  // ── Home Elevadores ── 8 Posts · 8 Reels ────────────
  { i: 1037, c: 'Home Elevadores', dt: d( 2), tp: 'Post', n: 'Elevador residencial: conforto no inverno',    s: s( 2) },
  { i: 1038, c: 'Home Elevadores', dt: d( 5), tp: 'Post', n: 'Dia dos Namorados — presente especial',        s: s( 5) },
  { i: 1039, c: 'Home Elevadores', dt: d( 9), tp: 'Post', n: 'Modelos compactos para sua casa',              s: s( 9) },
  { i: 1040, c: 'Home Elevadores', dt: d(13), tp: 'Post', n: 'Instalação sem quebra-quebra',                 s: s(13) },
  { i: 1041, c: 'Home Elevadores', dt: d(17), tp: 'Post', n: 'Manutenção preventiva de inverno',             s: s(17) },
  { i: 1042, c: 'Home Elevadores', dt: d(21), tp: 'Post', n: 'Planeje sua obra nas férias de julho',         s: s(21) },
  { i: 1043, c: 'Home Elevadores', dt: d(25), tp: 'Post', n: 'Consultoria gratuita em junho',                s: s(25) },
  { i: 1044, c: 'Home Elevadores', dt: d(29), tp: 'Post', n: 'Tecnologia e acessibilidade',                  s: s(29) },
  { i: 1045, c: 'Home Elevadores', dt: d( 3), tp: 'Reel', n: 'Como funciona nosso elevador',                 s: s( 3) },
  { i: 1046, c: 'Home Elevadores', dt: d( 7), tp: 'Reel', n: 'Instalação residencial ao vivo',               s: s( 7) },
  { i: 1047, c: 'Home Elevadores', dt: d(11), tp: 'Reel', n: 'Modelos disponíveis 2026',                     s: s(11) },
  { i: 1048, c: 'Home Elevadores', dt: d(15), tp: 'Reel', n: 'Depoimento de cliente satisfeito',             s: s(15) },
  { i: 1049, c: 'Home Elevadores', dt: d(19), tp: 'Reel', n: 'Antes e depois da instalação',                 s: s(19) },
  { i: 1050, c: 'Home Elevadores', dt: d(23), tp: 'Reel', n: 'Tour: elevador panorâmico',                    s: s(23) },
  { i: 1051, c: 'Home Elevadores', dt: d(27), tp: 'Reel', n: 'Processo de instalação completo',              s: s(27) },
  { i: 1052, c: 'Home Elevadores', dt: d(30), tp: 'Reel', n: 'Benefícios para sua qualidade de vida',        s: s(30) },

  // ── Kátia Bigatello ── 12 Posts · 12 Reels ──────────
  { i: 1053, c: 'Kátia Bigatello', dt: d( 1), tp: 'Post', n: 'Make especial para Dia dos Namorados',         s: s( 1) },
  { i: 1054, c: 'Kátia Bigatello', dt: d( 3), tp: 'Post', n: 'Make de inverno: cores quentes',               s: s( 3) },
  { i: 1055, c: 'Kátia Bigatello', dt: d( 6), tp: 'Post', n: 'Tutorial lábios perfeitos no frio',            s: s( 6) },
  { i: 1056, c: 'Kátia Bigatello', dt: d( 9), tp: 'Post', n: 'Look para festa junina',                       s: s( 9) },
  { i: 1057, c: 'Kátia Bigatello', dt: d(12), tp: 'Post', n: 'Make romântica — Dia dos Namorados',           s: s(12) },
  { i: 1058, c: 'Kátia Bigatello', dt: d(15), tp: 'Post', n: 'Cuidados com a pele no frio',                  s: s(15) },
  { i: 1059, c: 'Kátia Bigatello', dt: d(17), tp: 'Post', n: 'Make estilo country junino',                   s: s(17) },
  { i: 1060, c: 'Kátia Bigatello', dt: d(20), tp: 'Post', n: 'Tendências de beleza no inverno',              s: s(20) },
  { i: 1061, c: 'Kátia Bigatello', dt: d(22), tp: 'Post', n: 'Make simples para o dia a dia',                s: s(22) },
  { i: 1062, c: 'Kátia Bigatello', dt: d(25), tp: 'Post', n: 'Cores da temporada junina',                    s: s(25) },
  { i: 1063, c: 'Kátia Bigatello', dt: d(27), tp: 'Post', n: 'Make para formatura de julho',                 s: s(27) },
  { i: 1064, c: 'Kátia Bigatello', dt: d(30), tp: 'Post', n: 'Fechamento de junho: melhores looks',          s: s(30) },
  { i: 1065, c: 'Kátia Bigatello', dt: d( 2), tp: 'Reel', n: 'Tutorial: make romântica',                     s: s( 2) },
  { i: 1066, c: 'Kátia Bigatello', dt: d( 4), tp: 'Reel', n: 'Transformação para o Dia dos Namorados',      s: s( 4) },
  { i: 1067, c: 'Kátia Bigatello', dt: d( 7), tp: 'Reel', n: 'Preparação da pele no inverno',               s: s( 7) },
  { i: 1068, c: 'Kátia Bigatello', dt: d(10), tp: 'Reel', n: 'Make para festa junina',                       s: s(10) },
  { i: 1069, c: 'Kátia Bigatello', dt: d(13), tp: 'Reel', n: 'Produtos que uso todo dia',                    s: s(13) },
  { i: 1070, c: 'Kátia Bigatello', dt: d(16), tp: 'Reel', n: 'Tutorial lábios nude para o frio',             s: s(16) },
  { i: 1071, c: 'Kátia Bigatello', dt: d(19), tp: 'Reel', n: 'Make estilo country/junino',                   s: s(19) },
  { i: 1072, c: 'Kátia Bigatello', dt: d(21), tp: 'Reel', n: 'Correção de imperfeições',                     s: s(21) },
  { i: 1073, c: 'Kátia Bigatello', dt: d(24), tp: 'Reel', n: '5 dicas de make para festas juninas',          s: s(24) },
  { i: 1074, c: 'Kátia Bigatello', dt: d(26), tp: 'Reel', n: 'Blush placement para o inverno',               s: s(26) },
  { i: 1075, c: 'Kátia Bigatello', dt: d(28), tp: 'Reel', n: 'Make para formatura',                          s: s(28) },
  { i: 1076, c: 'Kátia Bigatello', dt: d(30), tp: 'Reel', n: 'Rotina de cuidados no frio',                   s: s(30) },

  // ── Lareiras Grill ── 8 Posts · 8 Reels ─────────────
  { i: 1077, c: 'Lareiras Grill', dt: d( 2), tp: 'Post', n: 'Destaque do fim de semana',                     s: s( 2) },
  { i: 1078, c: 'Lareiras Grill', dt: d( 5), tp: 'Post', n: 'Fondue especial do inverno',                    s: s( 5) },
  { i: 1079, c: 'Lareiras Grill', dt: d( 8), tp: 'Post', n: 'Cardápio de inverno — novidades',               s: s( 8) },
  { i: 1080, c: 'Lareiras Grill', dt: d(12), tp: 'Post', n: 'Jantar especial Dia dos Namorados',             s: s(12) },
  { i: 1081, c: 'Lareiras Grill', dt: d(16), tp: 'Post', n: 'Arroz de leite caramelado',                     s: s(16) },
  { i: 1082, c: 'Lareiras Grill', dt: d(19), tp: 'Post', n: 'Festa Junina — pratos típicos',                 s: s(19) },
  { i: 1083, c: 'Lareiras Grill', dt: d(23), tp: 'Post', n: 'São João — ceia especial',                      s: s(23) },
  { i: 1084, c: 'Lareiras Grill', dt: d(26), tp: 'Post', n: 'Encerramento de junho',                         s: s(26) },
  { i: 1085, c: 'Lareiras Grill', dt: d( 3), tp: 'Reel', n: 'Tour pelo restaurante no inverno',              s: s( 3) },
  { i: 1086, c: 'Lareiras Grill', dt: d( 7), tp: 'Reel', n: 'Lareiras Grill — ambiente aconchegante',        s: s( 7) },
  { i: 1087, c: 'Lareiras Grill', dt: d(10), tp: 'Reel', n: 'Meme do inverno',                               s: s(10) },
  { i: 1088, c: 'Lareiras Grill', dt: d(14), tp: 'Reel', n: 'À la carte especial de junho',                  s: s(14) },
  { i: 1089, c: 'Lareiras Grill', dt: d(17), tp: 'Reel', n: 'Feedback de clientes',                          s: s(17) },
  { i: 1090, c: 'Lareiras Grill', dt: d(20), tp: 'Reel', n: 'Especial junino',                               s: s(20) },
  { i: 1091, c: 'Lareiras Grill', dt: d(24), tp: 'Reel', n: 'Influencer kerges na quadrilha',                s: s(24) },
  { i: 1092, c: 'Lareiras Grill', dt: d(27), tp: 'Reel', n: 'Meme sem 1 real no São João',                   s: s(27) },

  // ── Luthita ── 8 Posts · 8 Reels ────────────────────
  { i: 1093, c: 'Luthita', dt: d( 1), tp: 'Post', n: 'Lookbook de inverno',                                  s: s( 1) },
  { i: 1094, c: 'Luthita', dt: d( 5), tp: 'Post', n: 'Novidade na coleção de frio',                          s: s( 5) },
  { i: 1095, c: 'Luthita', dt: d( 8), tp: 'Post', n: 'Look para festa junina',                               s: s( 8) },
  { i: 1096, c: 'Luthita', dt: d(12), tp: 'Post', n: 'Estilo para o Dia dos Namorados',                      s: s(12) },
  { i: 1097, c: 'Luthita', dt: d(16), tp: 'Post', n: 'Peças de inverno em destaque',                         s: s(16) },
  { i: 1098, c: 'Luthita', dt: d(20), tp: 'Post', n: 'Look casual aconchegante',                             s: s(20) },
  { i: 1099, c: 'Luthita', dt: d(24), tp: 'Post', n: 'Estilo arraiá — looks juninos',                        s: s(24) },
  { i: 1100, c: 'Luthita', dt: d(28), tp: 'Post', n: 'Peças da coleção de férias',                           s: s(28) },
  { i: 1101, c: 'Luthita', dt: d( 3), tp: 'Reel', n: 'Unboxing coleção de inverno',                          s: s( 3) },
  { i: 1102, c: 'Luthita', dt: d( 6), tp: 'Reel', n: 'Como usar casacos e sobreposições',                    s: s( 6) },
  { i: 1103, c: 'Luthita', dt: d(10), tp: 'Reel', n: 'Look do dia para o frio',                              s: s(10) },
  { i: 1104, c: 'Luthita', dt: d(14), tp: 'Reel', n: 'Styling tips — Dia dos Namorados',                     s: s(14) },
  { i: 1105, c: 'Luthita', dt: d(18), tp: 'Reel', n: 'Novidades de inverno chegando',                        s: s(18) },
  { i: 1106, c: 'Luthita', dt: d(22), tp: 'Reel', n: 'Haul de roupas de frio',                               s: s(22) },
  { i: 1107, c: 'Luthita', dt: d(26), tp: 'Reel', n: '5 looks para festa junina',                            s: s(26) },
  { i: 1108, c: 'Luthita', dt: d(30), tp: 'Reel', n: 'Looks para as férias de julho',                        s: s(30) },

  // ── LuzioPan ── 8 Posts · 8 Reels ───────────────────
  { i: 1109, c: 'LuzioPan', dt: d( 4), tp: 'Post', n: 'Cuca de festa junina com Prodipanni',                s: s( 4) },
  { i: 1110, c: 'LuzioPan', dt: d( 7), tp: 'Post', n: 'Macarrão para a ceia junina',                        s: s( 7) },
  { i: 1111, c: 'LuzioPan', dt: d(11), tp: 'Post', n: 'Prodipanni no cardápio de inverno',                  s: s(11) },
  { i: 1112, c: 'LuzioPan', dt: d(14), tp: 'Post', n: 'Bolo de milho com Prodipanni',                       s: s(14) },
  { i: 1113, c: 'LuzioPan', dt: d(18), tp: 'Post', n: 'Junho é o mês de vender mais',                       s: s(18) },
  { i: 1114, c: 'LuzioPan', dt: d(21), tp: 'Post', n: 'DONO DE PADARIA — especial São João',                s: s(21) },
  { i: 1115, c: 'LuzioPan', dt: d(25), tp: 'Post', n: 'Venda mais com o Prodipanni no arraiá',              s: s(25) },
  { i: 1116, c: 'LuzioPan', dt: d(28), tp: 'Post', n: 'Desenforme perfeito para festas juninas',            s: s(28) },
  { i: 1117, c: 'LuzioPan', dt: d( 2), tp: 'Reel', n: 'Para quem é o Prodipanni',                           s: s( 2) },
  { i: 1118, c: 'LuzioPan', dt: d( 5), tp: 'Reel', n: 'Quem é o Luzio — especial junho',                   s: s( 5) },
  { i: 1119, c: 'LuzioPan', dt: d( 9), tp: 'Reel', n: 'Prodipanni bolo de milho',                           s: s( 9) },
  { i: 1120, c: 'LuzioPan', dt: d(12), tp: 'Reel', n: 'Prodipanni cuca junina',                             s: s(12) },
  { i: 1121, c: 'LuzioPan', dt: d(16), tp: 'Reel', n: 'Prodipanni para festa junina',                       s: s(16) },
  { i: 1122, c: 'LuzioPan', dt: d(19), tp: 'Reel', n: 'Prodipanni paçoca cake',                             s: s(19) },
  { i: 1123, c: 'LuzioPan', dt: d(26), tp: 'Reel', n: 'MEME ARRAIÁ',                                        s: s(26) },
  { i: 1124, c: 'LuzioPan', dt: d(30), tp: 'Reel', n: 'Como fazer bolo de milho perfeito',                  s: s(30) },

  // ── Magia dos Temáticos ── 6 Posts · 6 Reels ────────
  { i: 1125, c: 'Magia dos Temáticos', dt: d( 7), tp: 'Post', n: 'Festa temática de São João',               s: s( 7) },
  { i: 1126, c: 'Magia dos Temáticos', dt: d(12), tp: 'Post', n: 'Festa especial Dia dos Namorados',         s: s(12) },
  { i: 1127, c: 'Magia dos Temáticos', dt: d(15), tp: 'Post', n: 'Reserve sua data para julho',              s: s(15) },
  { i: 1128, c: 'Magia dos Temáticos', dt: d(21), tp: 'Post', n: 'Festa junina completa — tudo incluso',     s: s(21) },
  { i: 1129, c: 'Magia dos Temáticos', dt: d(24), tp: 'Post', n: 'São João — decoração temática',            s: s(24) },
  { i: 1130, c: 'Magia dos Temáticos', dt: d(27), tp: 'Post', n: 'Pacote de festas para julho',              s: s(27) },
  { i: 1131, c: 'Magia dos Temáticos', dt: d( 2), tp: 'Reel', n: 'Conheça a Magia dos Temáticos',            s: s( 2) },
  { i: 1132, c: 'Magia dos Temáticos', dt: d( 4), tp: 'Reel', n: 'Não é só uma festa, é uma experiência',   s: s( 4) },
  { i: 1133, c: 'Magia dos Temáticos', dt: d( 8), tp: 'Reel', n: 'Meme: como organizar um arraiá',           s: s( 8) },
  { i: 1134, c: 'Magia dos Temáticos', dt: d(16), tp: 'Reel', n: 'Você nunca viu um arraiá assim',           s: s(16) },
  { i: 1135, c: 'Magia dos Temáticos', dt: d(20), tp: 'Reel', n: 'Bastidores da decoração junina',           s: s(20) },
  { i: 1136, c: 'Magia dos Temáticos', dt: d(28), tp: 'Reel', n: 'Festa de aniversário temática',            s: s(28) },

  // ── Padaria R.A ── 4 Posts · 4 Reels ────────────────
  { i: 1137, c: 'Padaria R.A', dt: d( 3), tp: 'Post', n: 'Cuca e paçoca — especial Festa Junina',           s: s( 3) },
  { i: 1138, c: 'Padaria R.A', dt: d(10), tp: 'Post', n: 'Bolo de milho especial',                           s: s(10) },
  { i: 1139, c: 'Padaria R.A', dt: d(17), tp: 'Post', n: 'Pão quentinho no frio',                            s: s(17) },
  { i: 1140, c: 'Padaria R.A', dt: d(24), tp: 'Post', n: 'Ceia de São João — encomendas abertas',            s: s(24) },
  { i: 1141, c: 'Padaria R.A', dt: d( 6), tp: 'Reel', n: 'Padaria R.A — especial inverno',                   s: s( 6) },
  { i: 1142, c: 'Padaria R.A', dt: d(14), tp: 'Reel', n: 'Delícias juninas na padaria',                      s: s(14) },
  { i: 1143, c: 'Padaria R.A', dt: d(20), tp: 'Reel', n: 'O café que você merece no frio',                   s: s(20) },
  { i: 1144, c: 'Padaria R.A', dt: d(27), tp: 'Reel', n: 'Vem tomar um quentão comigo',                      s: s(27) },

  // ── Pousada Dukuka ── 6 Posts · 12 Reels ────────────
  { i: 1145, c: 'Pousada Dukuka', dt: d( 4), tp: 'Post', n: 'Pacote especial de inverno',                   s: s( 4) },
  { i: 1146, c: 'Pousada Dukuka', dt: d( 8), tp: 'Post', n: 'Dia dos Namorados na pousada',                 s: s( 8) },
  { i: 1147, c: 'Pousada Dukuka', dt: d(13), tp: 'Post', n: 'Festa Junina na pousada',                      s: s(13) },
  { i: 1148, c: 'Pousada Dukuka', dt: d(18), tp: 'Post', n: 'Chalé aconchegante no frio',                   s: s(18) },
  { i: 1149, c: 'Pousada Dukuka', dt: d(24), tp: 'Post', n: 'São João — fogueira e quadrilha',              s: s(24) },
  { i: 1150, c: 'Pousada Dukuka', dt: d(29), tp: 'Post', n: 'Férias de julho — reserve já!',                s: s(29) },
  { i: 1151, c: 'Pousada Dukuka', dt: d( 1), tp: 'Reel', n: 'Tour pela pousada no inverno',                 s: s( 1) },
  { i: 1152, c: 'Pousada Dukuka', dt: d( 4), tp: 'Reel', n: 'Kaique influencer — especial junho',           s: s( 4) },
  { i: 1153, c: 'Pousada Dukuka', dt: d( 8), tp: 'Reel', n: 'Lareira e conforto no frio',                   s: s( 8) },
  { i: 1154, c: 'Pousada Dukuka', dt: d(12), tp: 'Reel', n: 'Surpresa de Dia dos Namorados',                s: s(12) },
  { i: 1155, c: 'Pousada Dukuka', dt: d(15), tp: 'Reel', n: 'Festa junina na pousada',                      s: s(15) },
  { i: 1156, c: 'Pousada Dukuka', dt: d(18), tp: 'Reel', n: 'Natureza no inverno',                          s: s(18) },
  { i: 1157, c: 'Pousada Dukuka', dt: d(20), tp: 'Reel', n: 'Depoimentos de casais',                        s: s(20) },
  { i: 1158, c: 'Pousada Dukuka', dt: d(22), tp: 'Reel', n: 'Passeios de inverno pela região',              s: s(22) },
  { i: 1159, c: 'Pousada Dukuka', dt: d(25), tp: 'Reel', n: 'Trilhas na serra em junho',                    s: s(25) },
  { i: 1160, c: 'Pousada Dukuka', dt: d(27), tp: 'Reel', n: 'Jardim da pousada florido',                    s: s(27) },
  { i: 1161, c: 'Pousada Dukuka', dt: d(29), tp: 'Reel', n: 'Pôr do sol de inverno na pousada',             s: s(29) },
  { i: 1162, c: 'Pousada Dukuka', dt: d(30), tp: 'Reel', n: 'Fim de semana perfeito no frio',               s: s(30) },

  // ── Quero Bolo ── 4 Posts · 4 Reels ─────────────────
  { i: 1163, c: 'Quero Bolo', dt: d( 5), tp: 'Post', n: 'Bolo de milho especial de junho',                  s: s( 5) },
  { i: 1164, c: 'Quero Bolo', dt: d(12), tp: 'Post', n: 'Bolo para o Dia dos Namorados',                    s: s(12) },
  { i: 1165, c: 'Quero Bolo', dt: d(19), tp: 'Post', n: 'Encomendas para festa junina',                     s: s(19) },
  { i: 1166, c: 'Quero Bolo', dt: d(26), tp: 'Post', n: 'Sabores de inverno — peça o seu',                  s: s(26) },
  { i: 1167, c: 'Quero Bolo', dt: d( 8), tp: 'Reel', n: 'Como fazemos o bolo de milho',                     s: s( 8) },
  { i: 1168, c: 'Quero Bolo', dt: d(15), tp: 'Reel', n: 'Decoração para festa junina',                      s: s(15) },
  { i: 1169, c: 'Quero Bolo', dt: d(22), tp: 'Reel', n: 'Bolo temático de arraiá',                          s: s(22) },
  { i: 1170, c: 'Quero Bolo', dt: d(29), tp: 'Reel', n: 'Escolha seu sabor para julho',                     s: s(29) },

  // ── ViniPlas ── 8 Posts · 8 Reels ───────────────────
  { i: 1171, c: 'ViniPlas', dt: d( 2), tp: 'Post', n: 'Adesivos decorativos para o arraiá',                 s: s( 2) },
  { i: 1172, c: 'ViniPlas', dt: d( 6), tp: 'Post', n: 'Personalização para o Dia dos Namorados',            s: s( 6) },
  { i: 1173, c: 'ViniPlas', dt: d(10), tp: 'Post', n: 'Vinil para fachadas e espaços',                      s: s(10) },
  { i: 1174, c: 'ViniPlas', dt: d(14), tp: 'Post', n: 'Soluções em plástico para eventos',                  s: s(14) },
  { i: 1175, c: 'ViniPlas', dt: d(18), tp: 'Post', n: 'Novidades da linha para julho',                      s: s(18) },
  { i: 1176, c: 'ViniPlas', dt: d(22), tp: 'Post', n: 'Qualidade garantida em cada projeto',                s: s(22) },
  { i: 1177, c: 'ViniPlas', dt: d(26), tp: 'Post', n: 'Orçamento expresso — sem burocracia',                s: s(26) },
  { i: 1178, c: 'ViniPlas', dt: d(30), tp: 'Post', n: 'Projeto especial de fim de mês',                     s: s(30) },
  { i: 1179, c: 'ViniPlas', dt: d( 4), tp: 'Reel', n: 'Aplicação de adesivo decorativo',                    s: s( 4) },
  { i: 1180, c: 'ViniPlas', dt: d( 8), tp: 'Reel', n: 'Processo de produção ao vivo',                       s: s( 8) },
  { i: 1181, c: 'ViniPlas', dt: d(12), tp: 'Reel', n: 'Antes e depois',                                     s: s(12) },
  { i: 1182, c: 'ViniPlas', dt: d(16), tp: 'Reel', n: 'Personalização para festa junina',                   s: s(16) },
  { i: 1183, c: 'ViniPlas', dt: d(20), tp: 'Reel', n: 'Tour pela fábrica',                                  s: s(20) },
  { i: 1184, c: 'ViniPlas', dt: d(24), tp: 'Reel', n: 'Produto mais vendido do mês',                        s: s(24) },
  { i: 1185, c: 'ViniPlas', dt: d(28), tp: 'Reel', n: 'Impressão digital de alta qualidade',                s: s(28) },
  { i: 1186, c: 'ViniPlas', dt: d(30), tp: 'Reel', n: 'Resultado final — cliente satisfeito',               s: s(30) },

  // ── Rosângela Varas ── 6 Posts · 6 Reels ────────────
  { i: 1187, c: 'Rosângela Varas', dt: d( 6), tp: 'Post', n: 'Dieta junina: armadilhas que você não vê',   s: s( 6) },
  { i: 1188, c: 'Rosângela Varas', dt: d(11), tp: 'Post', n: 'Saúde hormonal no inverno',                  s: s(11) },
  { i: 1189, c: 'Rosângela Varas', dt: d(16), tp: 'Post', n: 'Exercícios na estação fria',                 s: s(16) },
  { i: 1190, c: 'Rosângela Varas', dt: d(20), tp: 'Post', n: 'Como manter o peso nas festas juninas',      s: s(20) },
  { i: 1191, c: 'Rosângela Varas', dt: d(24), tp: 'Post', n: 'São João sem culpa: guia prático',           s: s(24) },
  { i: 1192, c: 'Rosângela Varas', dt: d(27), tp: 'Post', n: 'Cuide da sua saúde nas férias',              s: s(27) },
  { i: 1193, c: 'Rosângela Varas', dt: d( 5), tp: 'Reel', n: 'Efeitos do frio no metabolismo',            s: s( 5) },
  { i: 1194, c: 'Rosângela Varas', dt: d( 9), tp: 'Reel', n: 'Mais é claro — especial inverno',            s: s( 9) },
  { i: 1195, c: 'Rosângela Varas', dt: d(13), tp: 'Reel', n: 'Hormônios e clima',                          s: s(13) },
  { i: 1196, c: 'Rosângela Varas', dt: d(19), tp: 'Reel', n: 'Entrevista — perda de peso no inverno',      s: s(19) },
  { i: 1197, c: 'Rosângela Varas', dt: d(23), tp: 'Reel', n: 'Festa junina e saúde',                       s: s(23) },
  { i: 1198, c: 'Rosângela Varas', dt: d(25), tp: 'Reel', n: 'Institucional — junho',                      s: s(25) },

  // ── Compostela ── 8 Posts · 8 Reels ─────────────────
  { i: 1199, c: 'Compostela', dt: d( 1), tp: 'Post', n: 'Menu de inverno',                                  s: s( 1) },
  { i: 1200, c: 'Compostela', dt: d( 5), tp: 'Post', n: 'Ambiente especial no frio',                        s: s( 5) },
  { i: 1201, c: 'Compostela', dt: d( 9), tp: 'Post', n: 'Reserve sua mesa — Dia dos Namorados',             s: s( 9) },
  { i: 1202, c: 'Compostela', dt: d(13), tp: 'Post', n: 'Jantar especial 12 de junho',                      s: s(13) },
  { i: 1203, c: 'Compostela', dt: d(17), tp: 'Post', n: 'Novidade no cardápio junino',                      s: s(17) },
  { i: 1204, c: 'Compostela', dt: d(21), tp: 'Post', n: 'Destaque da semana',                               s: s(21) },
  { i: 1205, c: 'Compostela', dt: d(25), tp: 'Post', n: 'Promoção de fim de mês',                           s: s(25) },
  { i: 1206, c: 'Compostela', dt: d(29), tp: 'Post', n: 'Grupos e eventos para julho',                      s: s(29) },
  { i: 1207, c: 'Compostela', dt: d( 3), tp: 'Reel', n: 'Tour pelo espaço no inverno',                      s: s( 3) },
  { i: 1208, c: 'Compostela', dt: d( 7), tp: 'Reel', n: 'Preparo dos pratos especiais',                     s: s( 7) },
  { i: 1209, c: 'Compostela', dt: d(11), tp: 'Reel', n: 'Experiência dos clientes',                         s: s(11) },
  { i: 1210, c: 'Compostela', dt: d(15), tp: 'Reel', n: 'Cardápio de inverno em destaque',                  s: s(15) },
  { i: 1211, c: 'Compostela', dt: d(19), tp: 'Reel', n: 'Como chegar ao Compostela',                        s: s(19) },
  { i: 1212, c: 'Compostela', dt: d(23), tp: 'Reel', n: 'Especial do chef — São João',                      s: s(23) },
  { i: 1213, c: 'Compostela', dt: d(27), tp: 'Reel', n: 'Noite especial de festa junina',                   s: s(27) },
  { i: 1214, c: 'Compostela', dt: d(30), tp: 'Reel', n: 'Ambiente rústico e aconchegante',                  s: s(30) },

  // ── Suh Maya ── 4 Posts · 8 Reels ───────────────────
  { i: 1215, c: 'Suh Maya', dt: d( 4), tp: 'Post', n: 'Show especial de Festa Junina',                      s: s( 4) },
  { i: 1216, c: 'Suh Maya', dt: d(18), tp: 'Post', n: 'Dica musical para o São João',                       s: s(18) },
  { i: 1217, c: 'Suh Maya', dt: d(24), tp: 'Post', n: 'São João — ao vivo no arraiá',                       s: s(24) },
  { i: 1218, c: 'Suh Maya', dt: d(27), tp: 'Post', n: 'Bastidores do arraiá',                               s: s(27) },
  { i: 1219, c: 'Suh Maya', dt: d( 1), tp: 'Reel', n: 'De qual cidade você é',                              s: s( 1) },
  { i: 1220, c: 'Suh Maya', dt: d(11), tp: 'Reel', n: 'Agora que o forró começou',                          s: s(11) },
  { i: 1221, c: 'Suh Maya', dt: d(13), tp: 'Reel', n: 'Postando 10mil composições juninas',                 s: s(13) },
  { i: 1222, c: 'Suh Maya', dt: d(15), tp: 'Reel', n: 'TBT show de São João do ano passado',                s: s(15) },
  { i: 1223, c: 'Suh Maya', dt: d(17), tp: 'Reel', n: 'De qual cidade você é — v2',                         s: s(17) },
  { i: 1224, c: 'Suh Maya', dt: d(21), tp: 'Reel', n: 'Será... o papo que rola no arraiá',                  s: s(21) },
  { i: 1225, c: 'Suh Maya', dt: d(25), tp: 'Reel', n: 'Só quem não veio ao show',                           s: s(25) },
  { i: 1226, c: 'Suh Maya', dt: d(29), tp: 'Reel', n: 'Deixa eu cantar um forró',                           s: s(29) },
]

// ── Julho 2026 — IDs 2001-2226 ───────────────────────────────────────────────

const d7 = (day: number) => new Date(2026, 6, day)

export const DATA_JULHO: ContentItem[] = [

  // ── Casa de Ração 2 Irmãos ── 4 Posts · 4 Reels ─────
  { i: 2001, c: 'Casa de Ração 2 Irmãos', dt: d7( 2), tp: 'Post', n: 'Pets nas férias: como cuidar no frio',     s: 0 },
  { i: 2002, c: 'Casa de Ração 2 Irmãos', dt: d7( 9), tp: 'Post', n: 'Promoção julho — ração premium',            s: 0 },
  { i: 2003, c: 'Casa de Ração 2 Irmãos', dt: d7(16), tp: 'Post', n: 'Dia do Amigo com seu pet',                  s: 0 },
  { i: 2004, c: 'Casa de Ração 2 Irmãos', dt: d7(23), tp: 'Post', n: 'Novidades de inverno na loja',              s: 0 },
  { i: 2005, c: 'Casa de Ração 2 Irmãos', dt: d7( 5), tp: 'Reel', n: 'Pets mais fofos das férias',                s: 0 },
  { i: 2006, c: 'Casa de Ração 2 Irmãos', dt: d7(11), tp: 'Reel', n: 'Como manter o pet aquecido no inverno',     s: 0 },
  { i: 2007, c: 'Casa de Ração 2 Irmãos', dt: d7(19), tp: 'Reel', n: 'Unboxing: novos produtos de julho',         s: 0 },
  { i: 2008, c: 'Casa de Ração 2 Irmãos', dt: d7(26), tp: 'Reel', n: 'Dia do Motorista — pet no carro',           s: 0 },

  // ── Chalés Alto da Represa ── 4 Posts · 4 Reels ─────
  { i: 2009, c: 'Chalés Alto da Represa', dt: d7( 1), tp: 'Post', n: 'Férias de julho no chalé — últimas vagas',  s: 0 },
  { i: 2010, c: 'Chalés Alto da Represa', dt: d7( 8), tp: 'Post', n: 'Inverno perfeito na represa',               s: 0 },
  { i: 2011, c: 'Chalés Alto da Represa', dt: d7(15), tp: 'Post', n: 'Pacote especial Dia do Amigo',              s: 0 },
  { i: 2012, c: 'Chalés Alto da Represa', dt: d7(22), tp: 'Post', n: 'Agosto se aproxima — reserve o seu!',       s: 0 },
  { i: 2013, c: 'Chalés Alto da Represa', dt: d7( 4), tp: 'Reel', n: 'Tour pelos chalés durante as férias',       s: 0 },
  { i: 2014, c: 'Chalés Alto da Represa', dt: d7(11), tp: 'Reel', n: 'Nascer do sol gelado na represa',           s: 0 },
  { i: 2015, c: 'Chalés Alto da Represa', dt: d7(18), tp: 'Reel', n: 'Família nas férias — momentos especiais',   s: 0 },
  { i: 2016, c: 'Chalés Alto da Represa', dt: d7(25), tp: 'Reel', n: 'Passeios ao redor da represa',              s: 0 },

  // ── Frango d'Água ── 8 Posts · 4 Reels ──────────────
  { i: 2017, c: "Frango d'Água", dt: d7( 1), tp: 'Post', n: 'Menu especial de férias',                            s: 0 },
  { i: 2018, c: "Frango d'Água", dt: d7( 4), tp: 'Post', n: 'Combinação do frio: caldo + frango',                 s: 0 },
  { i: 2019, c: "Frango d'Água", dt: d7( 8), tp: 'Post', n: 'Almoço executivo de julho',                          s: 0 },
  { i: 2020, c: "Frango d'Água", dt: d7(11), tp: 'Post', n: 'Prato do chef — edição inverno',                     s: 0 },
  { i: 2021, c: "Frango d'Água", dt: d7(15), tp: 'Post', n: 'Jantar em família nas férias',                       s: 0 },
  { i: 2022, c: "Frango d'Água", dt: d7(18), tp: 'Post', n: 'Promoção fim de semana',                             s: 0 },
  { i: 2023, c: "Frango d'Água", dt: d7(22), tp: 'Post', n: 'Dia do Amigo: venha com amigos!',                    s: 0 },
  { i: 2024, c: "Frango d'Água", dt: d7(28), tp: 'Post', n: 'Encerrando julho com sabor',                         s: 0 },
  { i: 2025, c: "Frango d'Água", dt: d7( 5), tp: 'Reel', n: 'Preparo do frango caipira especial',                 s: 0 },
  { i: 2026, c: "Frango d'Água", dt: d7(13), tp: 'Reel', n: 'Bastidores do almoço de domingo',                    s: 0 },
  { i: 2027, c: "Frango d'Água", dt: d7(21), tp: 'Reel', n: 'Caldo quente do inverno — receita',                  s: 0 },
  { i: 2028, c: "Frango d'Água", dt: d7(29), tp: 'Reel', n: 'Tour pela nossa cozinha — julho',                    s: 0 },

  // ── Hidro Elétrica Andrade ── 4 Posts · 4 Reels ─────
  { i: 2029, c: 'Hidro Elétrica Andrade', dt: d7( 2), tp: 'Post', n: 'Inverno e pico de consumo elétrico',        s: 0 },
  { i: 2030, c: 'Hidro Elétrica Andrade', dt: d7( 9), tp: 'Post', n: 'Energia solar: investimento para o frio',   s: 0 },
  { i: 2031, c: 'Hidro Elétrica Andrade', dt: d7(16), tp: 'Post', n: 'Obra concluída — cliente satisfeito',       s: 0 },
  { i: 2032, c: 'Hidro Elétrica Andrade', dt: d7(23), tp: 'Post', n: 'Orçamento gratuito — julho',                s: 0 },
  { i: 2033, c: 'Hidro Elétrica Andrade', dt: d7( 5), tp: 'Reel', n: 'Equipe em campo no inverno',                s: 0 },
  { i: 2034, c: 'Hidro Elétrica Andrade', dt: d7(12), tp: 'Reel', n: 'Instalação elétrica residencial',           s: 0 },
  { i: 2035, c: 'Hidro Elétrica Andrade', dt: d7(19), tp: 'Reel', n: 'Antes e depois: painéis solares',           s: 0 },
  { i: 2036, c: 'Hidro Elétrica Andrade', dt: d7(26), tp: 'Reel', n: 'Economia garantida mesmo no inverno',       s: 0 },

  // ── Home Elevadores ── 8 Posts · 8 Reels ────────────
  { i: 2037, c: 'Home Elevadores', dt: d7( 1), tp: 'Post', n: 'Elevador residencial: férias com conforto',        s: 0 },
  { i: 2038, c: 'Home Elevadores', dt: d7( 4), tp: 'Post', n: 'Modelos para casa de veraneio',                    s: 0 },
  { i: 2039, c: 'Home Elevadores', dt: d7( 8), tp: 'Post', n: 'Acessibilidade para toda a família',               s: 0 },
  { i: 2040, c: 'Home Elevadores', dt: d7(11), tp: 'Post', n: 'Manutenção preventiva — garanta a segurança',      s: 0 },
  { i: 2041, c: 'Home Elevadores', dt: d7(15), tp: 'Post', n: 'Projetos entregues em julho',                      s: 0 },
  { i: 2042, c: 'Home Elevadores', dt: d7(18), tp: 'Post', n: 'Elevador compacto para casas menores',             s: 0 },
  { i: 2043, c: 'Home Elevadores', dt: d7(22), tp: 'Post', n: 'Tecnologia e elegância juntas',                    s: 0 },
  { i: 2044, c: 'Home Elevadores', dt: d7(28), tp: 'Post', n: 'Feche agosto com seu elevador instalado',          s: 0 },
  { i: 2045, c: 'Home Elevadores', dt: d7( 2), tp: 'Reel', n: 'Instalação completa em 1 dia',                     s: 0 },
  { i: 2046, c: 'Home Elevadores', dt: d7( 6), tp: 'Reel', n: 'Tour por um projeto entregue',                     s: 0 },
  { i: 2047, c: 'Home Elevadores', dt: d7(10), tp: 'Reel', n: 'Como funciona nosso elevador residencial',         s: 0 },
  { i: 2048, c: 'Home Elevadores', dt: d7(14), tp: 'Reel', n: 'Depoimento de cliente — família feliz',            s: 0 },
  { i: 2049, c: 'Home Elevadores', dt: d7(17), tp: 'Reel', n: 'Antes e depois da instalação',                     s: 0 },
  { i: 2050, c: 'Home Elevadores', dt: d7(21), tp: 'Reel', n: 'Cabine personalizada — veja as opções',            s: 0 },
  { i: 2051, c: 'Home Elevadores', dt: d7(24), tp: 'Reel', n: 'Segurança em primeiro lugar',                      s: 0 },
  { i: 2052, c: 'Home Elevadores', dt: d7(29), tp: 'Reel', n: 'Conforto para pais e filhos',                      s: 0 },

  // ── Kátia Bigatello ── 12 Posts · 12 Reels ──────────
  { i: 2053, c: 'Kátia Bigatello', dt: d7( 1), tp: 'Post', n: 'Pele hidratada no inverno — dicas essenciais',    s: 0 },
  { i: 2054, c: 'Kátia Bigatello', dt: d7( 3), tp: 'Post', n: 'Tratamento capilar para o frio',                  s: 0 },
  { i: 2055, c: 'Kátia Bigatello', dt: d7( 6), tp: 'Post', n: 'Limpeza de pele: por que fazer no inverno',       s: 0 },
  { i: 2056, c: 'Kátia Bigatello', dt: d7( 9), tp: 'Post', n: 'Promoção especial de julho',                      s: 0 },
  { i: 2057, c: 'Kátia Bigatello', dt: d7(11), tp: 'Post', n: 'Massagem relaxante nas férias',                   s: 0 },
  { i: 2058, c: 'Kátia Bigatello', dt: d7(14), tp: 'Post', n: 'Sobrancelha: tendências do inverno',              s: 0 },
  { i: 2059, c: 'Kátia Bigatello', dt: d7(16), tp: 'Post', n: 'Presente do Dia do Amigo — voucher estética',     s: 0 },
  { i: 2060, c: 'Kátia Bigatello', dt: d7(19), tp: 'Post', n: 'Micropigmentação: tire suas dúvidas',             s: 0 },
  { i: 2061, c: 'Kátia Bigatello', dt: d7(21), tp: 'Post', n: 'Agenda aberta — agende o seu horário',            s: 0 },
  { i: 2062, c: 'Kátia Bigatello', dt: d7(23), tp: 'Post', n: 'Antes e depois do mês de julho',                  s: 0 },
  { i: 2063, c: 'Kátia Bigatello', dt: d7(26), tp: 'Post', n: 'Cuidados de inverno para mãos e pés',             s: 0 },
  { i: 2064, c: 'Kátia Bigatello', dt: d7(29), tp: 'Post', n: 'Últimas vagas de julho',                          s: 0 },
  { i: 2065, c: 'Kátia Bigatello', dt: d7( 2), tp: 'Reel', n: 'Limpeza de pele passo a passo',                   s: 0 },
  { i: 2066, c: 'Kátia Bigatello', dt: d7( 5), tp: 'Reel', n: 'Transformação capilar — hidratação',              s: 0 },
  { i: 2067, c: 'Kátia Bigatello', dt: d7( 8), tp: 'Reel', n: 'Dia de spa — bastidores',                         s: 0 },
  { i: 2068, c: 'Kátia Bigatello', dt: d7(10), tp: 'Reel', n: 'Sobrancelha perfeita — antes e depois',           s: 0 },
  { i: 2069, c: 'Kátia Bigatello', dt: d7(13), tp: 'Reel', n: 'Massagem modeladora — resultados reais',          s: 0 },
  { i: 2070, c: 'Kátia Bigatello', dt: d7(15), tp: 'Reel', n: 'Micropigmentação: o processo completo',           s: 0 },
  { i: 2071, c: 'Kátia Bigatello', dt: d7(17), tp: 'Reel', n: 'Rotina de skincare para o inverno',               s: 0 },
  { i: 2072, c: 'Kátia Bigatello', dt: d7(20), tp: 'Reel', n: 'Cliente especial — depoimento',                   s: 0 },
  { i: 2073, c: 'Kátia Bigatello', dt: d7(22), tp: 'Reel', n: 'Unha em gel: novidades do inverno',               s: 0 },
  { i: 2074, c: 'Kátia Bigatello', dt: d7(24), tp: 'Reel', n: 'Design de sobrancelha ao vivo',                   s: 0 },
  { i: 2075, c: 'Kátia Bigatello', dt: d7(27), tp: 'Reel', n: 'Peeling: o que é e para quem é',                  s: 0 },
  { i: 2076, c: 'Kátia Bigatello', dt: d7(30), tp: 'Reel', n: 'Encerramento de julho — gratidão',                s: 0 },

  // ── Lareiras Grill ── 8 Posts · 8 Reels ─────────────
  { i: 2077, c: 'Lareiras Grill', dt: d7( 1), tp: 'Post', n: 'A lareira acesa e o churrasco perfeito',           s: 0 },
  { i: 2078, c: 'Lareiras Grill', dt: d7( 4), tp: 'Post', n: 'Férias de julho: churrasco em família',            s: 0 },
  { i: 2079, c: 'Lareiras Grill', dt: d7( 8), tp: 'Post', n: 'Corte especial de inverno',                        s: 0 },
  { i: 2080, c: 'Lareiras Grill', dt: d7(11), tp: 'Post', n: 'Rodízio completo nas férias',                      s: 0 },
  { i: 2081, c: 'Lareiras Grill', dt: d7(15), tp: 'Post', n: 'Reserva para grupos — julho',                      s: 0 },
  { i: 2082, c: 'Lareiras Grill', dt: d7(18), tp: 'Post', n: 'Menu especial Dia do Amigo',                       s: 0 },
  { i: 2083, c: 'Lareiras Grill', dt: d7(22), tp: 'Post', n: 'Prime: como identificar um bom corte',             s: 0 },
  { i: 2084, c: 'Lareiras Grill', dt: d7(28), tp: 'Post', n: 'Encerrando julho com muito sabor',                 s: 0 },
  { i: 2085, c: 'Lareiras Grill', dt: d7( 3), tp: 'Reel', n: 'Acendendo a lareira — ritual de inverno',          s: 0 },
  { i: 2086, c: 'Lareiras Grill', dt: d7( 6), tp: 'Reel', n: 'Picanha na brasa — modo de preparo',               s: 0 },
  { i: 2087, c: 'Lareiras Grill', dt: d7(10), tp: 'Reel', n: 'Experiência do cliente nas férias',                s: 0 },
  { i: 2088, c: 'Lareiras Grill', dt: d7(13), tp: 'Reel', n: 'Corte do chef — fraldinha no inverno',             s: 0 },
  { i: 2089, c: 'Lareiras Grill', dt: d7(17), tp: 'Reel', n: 'Mesa posta: clima de inverno no salão',            s: 0 },
  { i: 2090, c: 'Lareiras Grill', dt: d7(20), tp: 'Reel', n: 'Dia do Amigo: venha com a galera',                 s: 0 },
  { i: 2091, c: 'Lareiras Grill', dt: d7(24), tp: 'Reel', n: 'Processo da costela: 6h de brasa',                 s: 0 },
  { i: 2092, c: 'Lareiras Grill', dt: d7(29), tp: 'Reel', n: 'Bastidores do sábado cheio',                       s: 0 },

  // ── Luthita ── 8 Posts · 8 Reels ────────────────────
  { i: 2093, c: 'Luthita', dt: d7( 2), tp: 'Post', n: 'Soluções Luthita para o inverno',                        s: 0 },
  { i: 2094, c: 'Luthita', dt: d7( 6), tp: 'Post', n: 'Projeto entregue — cliente feliz',                       s: 0 },
  { i: 2095, c: 'Luthita', dt: d7( 9), tp: 'Post', n: 'Novidades de julho no portfólio',                        s: 0 },
  { i: 2096, c: 'Luthita', dt: d7(13), tp: 'Post', n: 'Por que escolher a Luthita?',                            s: 0 },
  { i: 2097, c: 'Luthita', dt: d7(16), tp: 'Post', n: 'Promoção especial Dia do Amigo',                         s: 0 },
  { i: 2098, c: 'Luthita', dt: d7(20), tp: 'Post', n: 'Diferenciais que fazem a diferença',                     s: 0 },
  { i: 2099, c: 'Luthita', dt: d7(23), tp: 'Post', n: 'Depoimento de cliente satisfeito',                       s: 0 },
  { i: 2100, c: 'Luthita', dt: d7(28), tp: 'Post', n: 'Planejamento de agosto — fale conosco',                  s: 0 },
  { i: 2101, c: 'Luthita', dt: d7( 3), tp: 'Reel', n: 'Processo de trabalho — bastidores',                      s: 0 },
  { i: 2102, c: 'Luthita', dt: d7( 7), tp: 'Reel', n: 'Resultado final — projeto julho',                        s: 0 },
  { i: 2103, c: 'Luthita', dt: d7(11), tp: 'Reel', n: 'Equipe em ação no inverno',                              s: 0 },
  { i: 2104, c: 'Luthita', dt: d7(14), tp: 'Reel', n: 'Antes e depois — transformação',                         s: 0 },
  { i: 2105, c: 'Luthita', dt: d7(17), tp: 'Reel', n: 'Detalhe que encanta o cliente',                          s: 0 },
  { i: 2106, c: 'Luthita', dt: d7(21), tp: 'Reel', n: 'Tour pelo escritório — dia a dia',                       s: 0 },
  { i: 2107, c: 'Luthita', dt: d7(24), tp: 'Reel', n: 'Entrega especial de julho',                              s: 0 },
  { i: 2108, c: 'Luthita', dt: d7(29), tp: 'Reel', n: 'Missão cumprida — fechando o mês',                       s: 0 },

  // ── LuzioPan ── 8 Posts · 8 Reels ───────────────────
  { i: 2109, c: 'LuzioPan', dt: d7( 1), tp: 'Post', n: 'Café da manhã nas férias — venha ao LuzioPan',          s: 0 },
  { i: 2110, c: 'LuzioPan', dt: d7( 5), tp: 'Post', n: 'Pão quentinho para o inverno',                          s: 0 },
  { i: 2111, c: 'LuzioPan', dt: d7( 9), tp: 'Post', n: 'Salgados especiais de julho',                           s: 0 },
  { i: 2112, c: 'LuzioPan', dt: d7(13), tp: 'Post', n: 'Torta do inverno — edição limitada',                    s: 0 },
  { i: 2113, c: 'LuzioPan', dt: d7(17), tp: 'Post', n: 'Encomendas para o Dia do Amigo',                        s: 0 },
  { i: 2114, c: 'LuzioPan', dt: d7(21), tp: 'Post', n: 'Dica do padeiro para o café da manhã',                  s: 0 },
  { i: 2115, c: 'LuzioPan', dt: d7(25), tp: 'Post', n: 'Sabores novos de agosto — prévia',                      s: 0 },
  { i: 2116, c: 'LuzioPan', dt: d7(29), tp: 'Post', n: 'Obrigado julho — até o próximo mês!',                   s: 0 },
  { i: 2117, c: 'LuzioPan', dt: d7( 3), tp: 'Reel', n: 'Pão saindo do forno — de manhã cedo',                   s: 0 },
  { i: 2118, c: 'LuzioPan', dt: d7( 7), tp: 'Reel', n: 'Como fazemos nosso croissant',                          s: 0 },
  { i: 2119, c: 'LuzioPan', dt: d7(11), tp: 'Reel', n: 'Cliente feliz no balcão — depoimento',                  s: 0 },
  { i: 2120, c: 'LuzioPan', dt: d7(15), tp: 'Reel', n: 'Processo do bolo de inverno',                           s: 0 },
  { i: 2121, c: 'LuzioPan', dt: d7(19), tp: 'Reel', n: 'Salgados favoritos dos clientes',                       s: 0 },
  { i: 2122, c: 'LuzioPan', dt: d7(23), tp: 'Reel', n: 'Bastidores da madrugada — produção',                    s: 0 },
  { i: 2123, c: 'LuzioPan', dt: d7(26), tp: 'Reel', n: 'Decoração da vitrine de julho',                         s: 0 },
  { i: 2124, c: 'LuzioPan', dt: d7(30), tp: 'Reel', n: 'Obrigado a todos os clientes!',                         s: 0 },

  // ── Magia dos Temáticos ── 6 Posts · 6 Reels ────────
  { i: 2125, c: 'Magia dos Temáticos', dt: d7( 3), tp: 'Post', n: 'Festas temáticas de férias para crianças',   s: 0 },
  { i: 2126, c: 'Magia dos Temáticos', dt: d7( 8), tp: 'Post', n: 'Decoração de inverno para sua festa',        s: 0 },
  { i: 2127, c: 'Magia dos Temáticos', dt: d7(14), tp: 'Post', n: 'Aniversário na época das férias — dicas',    s: 0 },
  { i: 2128, c: 'Magia dos Temáticos', dt: d7(19), tp: 'Post', n: 'Pacote completo: festa + decoração',         s: 0 },
  { i: 2129, c: 'Magia dos Temáticos', dt: d7(24), tp: 'Post', n: 'Agosto chegando — agenda o seu!',            s: 0 },
  { i: 2130, c: 'Magia dos Temáticos', dt: d7(29), tp: 'Post', n: 'Tema surpresa do mês de julho',              s: 0 },
  { i: 2131, c: 'Magia dos Temáticos', dt: d7( 5), tp: 'Reel', n: 'Montagem da decoração temática',             s: 0 },
  { i: 2132, c: 'Magia dos Temáticos', dt: d7(10), tp: 'Reel', n: 'Festa realizada — bastidores',               s: 0 },
  { i: 2133, c: 'Magia dos Temáticos', dt: d7(16), tp: 'Reel', n: 'Crianças encantadas — reação ao tema',       s: 0 },
  { i: 2134, c: 'Magia dos Temáticos', dt: d7(21), tp: 'Reel', n: 'Antes e depois da decoração',                s: 0 },
  { i: 2135, c: 'Magia dos Temáticos', dt: d7(26), tp: 'Reel', n: 'Tour pela festa temática',                   s: 0 },
  { i: 2136, c: 'Magia dos Temáticos', dt: d7(30), tp: 'Reel', n: 'Depoimento da família',                      s: 0 },

  // ── Padaria R.A ── 4 Posts · 4 Reels ────────────────
  { i: 2137, c: 'Padaria R.A', dt: d7( 4), tp: 'Post', n: 'Pão artesanal quentinho — manhãs de inverno',        s: 0 },
  { i: 2138, c: 'Padaria R.A', dt: d7(11), tp: 'Post', n: 'Café e bolo de inverno — combinação perfeita',       s: 0 },
  { i: 2139, c: 'Padaria R.A', dt: d7(18), tp: 'Post', n: 'Encomendas para o Dia do Amigo',                     s: 0 },
  { i: 2140, c: 'Padaria R.A', dt: d7(25), tp: 'Post', n: 'Novidades de agosto na padaria',                     s: 0 },
  { i: 2141, c: 'Padaria R.A', dt: d7( 6), tp: 'Reel', n: 'Fazendo pão na madrugada',                           s: 0 },
  { i: 2142, c: 'Padaria R.A', dt: d7(13), tp: 'Reel', n: 'Clientes favoritos das manhãs frias',                s: 0 },
  { i: 2143, c: 'Padaria R.A', dt: d7(20), tp: 'Reel', n: 'Torta de inverno saindo do forno',                   s: 0 },
  { i: 2144, c: 'Padaria R.A', dt: d7(27), tp: 'Reel', n: 'Vitrine linda — julho na padaria',                   s: 0 },

  // ── Pousada Dukuka ── 6 Posts · 12 Reels ────────────
  { i: 2145, c: 'Pousada Dukuka', dt: d7( 1), tp: 'Post', n: 'Férias lotadas — obrigado!',                      s: 0 },
  { i: 2146, c: 'Pousada Dukuka', dt: d7( 5), tp: 'Post', n: 'Inverno na pousada: experiência única',            s: 0 },
  { i: 2147, c: 'Pousada Dukuka', dt: d7(11), tp: 'Post', n: 'Família que veio nas férias — volta sempre',       s: 0 },
  { i: 2148, c: 'Pousada Dukuka', dt: d7(17), tp: 'Post', n: 'Fim de semana restante de julho',                  s: 0 },
  { i: 2149, c: 'Pousada Dukuka', dt: d7(22), tp: 'Post', n: 'Reserve agosto com desconto',                      s: 0 },
  { i: 2150, c: 'Pousada Dukuka', dt: d7(28), tp: 'Post', n: 'Até breve julho — agosto chegou!',                 s: 0 },
  { i: 2151, c: 'Pousada Dukuka', dt: d7( 2), tp: 'Reel', n: 'Tour pela pousada nas férias',                     s: 0 },
  { i: 2152, c: 'Pousada Dukuka', dt: d7( 4), tp: 'Reel', n: 'Kaique influencer — especial férias',              s: 0 },
  { i: 2153, c: 'Pousada Dukuka', dt: d7( 7), tp: 'Reel', n: 'Fogão a lenha no café da manhã',                   s: 0 },
  { i: 2154, c: 'Pousada Dukuka', dt: d7( 9), tp: 'Reel', n: 'Pôr do sol de inverno na pousada',                 s: 0 },
  { i: 2155, c: 'Pousada Dukuka', dt: d7(12), tp: 'Reel', n: 'Crianças em férias — atividades na pousada',       s: 0 },
  { i: 2156, c: 'Pousada Dukuka', dt: d7(14), tp: 'Reel', n: 'Natureza e inverno — trilha da pousada',           s: 0 },
  { i: 2157, c: 'Pousada Dukuka', dt: d7(16), tp: 'Reel', n: 'Lareira acesa — ambiente aconchegante',            s: 0 },
  { i: 2158, c: 'Pousada Dukuka', dt: d7(19), tp: 'Reel', n: 'Depoimento — família nas férias',                  s: 0 },
  { i: 2159, c: 'Pousada Dukuka', dt: d7(21), tp: 'Reel', n: 'Jardim da pousada no inverno',                     s: 0 },
  { i: 2160, c: 'Pousada Dukuka', dt: d7(24), tp: 'Reel', n: 'Amanhecer gelado com café quentinho',              s: 0 },
  { i: 2161, c: 'Pousada Dukuka', dt: d7(26), tp: 'Reel', n: 'Fim de semana perfeito no frio',                   s: 0 },
  { i: 2162, c: 'Pousada Dukuka', dt: d7(29), tp: 'Reel', n: 'Encerrando julho com gratidão',                    s: 0 },

  // ── Quero Bolo ── 4 Posts · 4 Reels ─────────────────
  { i: 2163, c: 'Quero Bolo', dt: d7( 4), tp: 'Post', n: 'Bolo de chocolate quente para o inverno',             s: 0 },
  { i: 2164, c: 'Quero Bolo', dt: d7(11), tp: 'Post', n: 'Bolo para aniversários das férias',                   s: 0 },
  { i: 2165, c: 'Quero Bolo', dt: d7(19), tp: 'Post', n: 'Encomenda para o Dia do Amigo',                       s: 0 },
  { i: 2166, c: 'Quero Bolo', dt: d7(26), tp: 'Post', n: 'Sabores novos de agosto — reserve já',                s: 0 },
  { i: 2167, c: 'Quero Bolo', dt: d7( 7), tp: 'Reel', n: 'Como fazemos o bolo de chocolate',                    s: 0 },
  { i: 2168, c: 'Quero Bolo', dt: d7(14), tp: 'Reel', n: 'Decoração especial de inverno',                       s: 0 },
  { i: 2169, c: 'Quero Bolo', dt: d7(22), tp: 'Reel', n: 'Bolo temático de aniversário',                        s: 0 },
  { i: 2170, c: 'Quero Bolo', dt: d7(29), tp: 'Reel', n: 'Escolha seu sabor para agosto',                       s: 0 },

  // ── ViniPlas ── 8 Posts · 8 Reels ───────────────────
  { i: 2171, c: 'ViniPlas', dt: d7( 2), tp: 'Post', n: 'Adesivos decorativos para o inverno',                   s: 0 },
  { i: 2172, c: 'ViniPlas', dt: d7( 5), tp: 'Post', n: 'Personalização em PVC para eventos de julho',           s: 0 },
  { i: 2173, c: 'ViniPlas', dt: d7( 9), tp: 'Post', n: 'Vinil para fachadas comerciais',                        s: 0 },
  { i: 2174, c: 'ViniPlas', dt: d7(12), tp: 'Post', n: 'Produtos mais pedidos de julho',                        s: 0 },
  { i: 2175, c: 'ViniPlas', dt: d7(16), tp: 'Post', n: 'Novidades para agosto no portfólio',                    s: 0 },
  { i: 2176, c: 'ViniPlas', dt: d7(20), tp: 'Post', n: 'Qualidade e prazo: nosso compromisso',                  s: 0 },
  { i: 2177, c: 'ViniPlas', dt: d7(24), tp: 'Post', n: 'Orçamento em 24h — fale conosco',                       s: 0 },
  { i: 2178, c: 'ViniPlas', dt: d7(29), tp: 'Post', n: 'Encerrando julho com resultados',                       s: 0 },
  { i: 2179, c: 'ViniPlas', dt: d7( 3), tp: 'Reel', n: 'Aplicação de vinil decorativo',                         s: 0 },
  { i: 2180, c: 'ViniPlas', dt: d7( 7), tp: 'Reel', n: 'Processo de produção ao vivo',                          s: 0 },
  { i: 2181, c: 'ViniPlas', dt: d7(11), tp: 'Reel', n: 'Antes e depois — projeto julho',                        s: 0 },
  { i: 2182, c: 'ViniPlas', dt: d7(15), tp: 'Reel', n: 'Impressão digital em destaque',                         s: 0 },
  { i: 2183, c: 'ViniPlas', dt: d7(19), tp: 'Reel', n: 'Tour pela fábrica',                                     s: 0 },
  { i: 2184, c: 'ViniPlas', dt: d7(23), tp: 'Reel', n: 'Produto mais vendido de julho',                         s: 0 },
  { i: 2185, c: 'ViniPlas', dt: d7(26), tp: 'Reel', n: 'Cliente satisfeito — resultado entregue',               s: 0 },
  { i: 2186, c: 'ViniPlas', dt: d7(30), tp: 'Reel', n: 'Fechando o mês com chave de ouro',                      s: 0 },

  // ── Rosângela Varas ── 6 Posts · 6 Reels ────────────
  { i: 2187, c: 'Rosângela Varas', dt: d7( 3), tp: 'Post', n: 'Saúde no inverno: cuidados para o metabolismo',  s: 0 },
  { i: 2188, c: 'Rosângela Varas', dt: d7( 8), tp: 'Post', n: 'Nutrição nas férias escolares',                  s: 0 },
  { i: 2189, c: 'Rosângela Varas', dt: d7(14), tp: 'Post', n: 'Exercícios para o inverno — como manter',        s: 0 },
  { i: 2190, c: 'Rosângela Varas', dt: d7(19), tp: 'Post', n: 'Dia do Amigo saudável — dicas práticas',         s: 0 },
  { i: 2191, c: 'Rosângela Varas', dt: d7(24), tp: 'Post', n: 'Alimentação de volta às aulas',                  s: 0 },
  { i: 2192, c: 'Rosângela Varas', dt: d7(29), tp: 'Post', n: 'Agosto começa: novos hábitos saudáveis',         s: 0 },
  { i: 2193, c: 'Rosângela Varas', dt: d7( 5), tp: 'Reel', n: 'Metabolismo e temperatura no frio',              s: 0 },
  { i: 2194, c: 'Rosângela Varas', dt: d7(10), tp: 'Reel', n: 'Cardápio saudável para o inverno',               s: 0 },
  { i: 2195, c: 'Rosângela Varas', dt: d7(16), tp: 'Reel', n: 'Consulta nutricional — o que esperar',           s: 0 },
  { i: 2196, c: 'Rosângela Varas', dt: d7(21), tp: 'Reel', n: 'Perda de peso: mitos e verdades',                s: 0 },
  { i: 2197, c: 'Rosângela Varas', dt: d7(25), tp: 'Reel', n: 'Receita funcional de inverno',                   s: 0 },
  { i: 2198, c: 'Rosângela Varas', dt: d7(28), tp: 'Reel', n: 'Institucional julho — gratidão',                 s: 0 },

  // ── Compostela ── 8 Posts · 8 Reels ─────────────────
  { i: 2199, c: 'Compostela', dt: d7( 1), tp: 'Post', n: 'Menu especial de férias',                              s: 0 },
  { i: 2200, c: 'Compostela', dt: d7( 5), tp: 'Post', n: 'Inverno no Compostela: ambiente perfeito',             s: 0 },
  { i: 2201, c: 'Compostela', dt: d7( 9), tp: 'Post', n: 'Prato do chef de julho',                               s: 0 },
  { i: 2202, c: 'Compostela', dt: d7(12), tp: 'Post', n: 'Jantar em família nas férias',                         s: 0 },
  { i: 2203, c: 'Compostela', dt: d7(16), tp: 'Post', n: 'Menu de inverno — novidades',                          s: 0 },
  { i: 2204, c: 'Compostela', dt: d7(20), tp: 'Post', n: 'Dia do Amigo: reservas abertas',                       s: 0 },
  { i: 2205, c: 'Compostela', dt: d7(24), tp: 'Post', n: 'Fim de semana especial — vaga limitada',               s: 0 },
  { i: 2206, c: 'Compostela', dt: d7(29), tp: 'Post', n: 'Eventos corporativos em agosto',                       s: 0 },
  { i: 2207, c: 'Compostela', dt: d7( 3), tp: 'Reel', n: 'Tour pelo restaurante nas férias',                     s: 0 },
  { i: 2208, c: 'Compostela', dt: d7( 7), tp: 'Reel', n: 'Preparo do prato especial de inverno',                 s: 0 },
  { i: 2209, c: 'Compostela', dt: d7(11), tp: 'Reel', n: 'Experiência dos clientes — depoimentos',               s: 0 },
  { i: 2210, c: 'Compostela', dt: d7(14), tp: 'Reel', n: 'Cardápio de inverno em detalhe',                       s: 0 },
  { i: 2211, c: 'Compostela', dt: d7(17), tp: 'Reel', n: 'Como chegar ao Compostela',                            s: 0 },
  { i: 2212, c: 'Compostela', dt: d7(21), tp: 'Reel', n: 'Chef prepara o especial da semana',                    s: 0 },
  { i: 2213, c: 'Compostela', dt: d7(25), tp: 'Reel', n: 'Reserva do Dia do Amigo — momentos',                   s: 0 },
  { i: 2214, c: 'Compostela', dt: d7(30), tp: 'Reel', n: 'Encerrando julho com gratidão',                        s: 0 },

  // ── Suh Maya ── 4 Posts · 8 Reels ───────────────────
  { i: 2215, c: 'Suh Maya', dt: d7( 5), tp: 'Post', n: 'Show de julho — agenda cheia',                           s: 0 },
  { i: 2216, c: 'Suh Maya', dt: d7(15), tp: 'Post', n: 'Bastidores do show de férias',                           s: 0 },
  { i: 2217, c: 'Suh Maya', dt: d7(22), tp: 'Post', n: 'Dia do Amigo — música ao vivo',                          s: 0 },
  { i: 2218, c: 'Suh Maya', dt: d7(28), tp: 'Post', n: 'Encerrando julho com muito forró',                       s: 0 },
  { i: 2219, c: 'Suh Maya', dt: d7( 1), tp: 'Reel', n: 'Começa julho — começa o forró',                          s: 0 },
  { i: 2220, c: 'Suh Maya', dt: d7( 8), tp: 'Reel', n: 'Reação do público no show',                              s: 0 },
  { i: 2221, c: 'Suh Maya', dt: d7(11), tp: 'Reel', n: 'Bastidores: soundcheck de inverno',                      s: 0 },
  { i: 2222, c: 'Suh Maya', dt: d7(14), tp: 'Reel', n: 'TBT show inesquecível de julho',                         s: 0 },
  { i: 2223, c: 'Suh Maya', dt: d7(18), tp: 'Reel', n: 'De qual cidade você é — v3',                             s: 0 },
  { i: 2224, c: 'Suh Maya', dt: d7(21), tp: 'Reel', n: 'Dia do Amigo: a música que une',                         s: 0 },
  { i: 2225, c: 'Suh Maya', dt: d7(25), tp: 'Reel', n: 'Só quem foi ao show sabe',                               s: 0 },
  { i: 2226, c: 'Suh Maya', dt: d7(29), tp: 'Reel', n: 'Forró até o fim de julho',                               s: 0 },
]
